// ════════════════════════════════════════
//  topics-data.js — 13 大主題核心資料
//  每主題：20 個單字 + 6~8 個句型 + 考試重點
// ════════════════════════════════════════
window.TOPICS_DATA = [

// ══════════════════════
//  1. Travel 旅遊篇
// ══════════════════════
{
  id:'travel', icon:'✈️', name:'Travel', nameTw:'旅遊篇',
  color:'#5b8fd4', desc:'機場、訂房、交通、行程安排',
  vocab:[
    {w:'itinerary',     m:'行程表',       e:'Please send me the updated travel itinerary.'},
    {w:'reservation',   m:'預訂、訂位',   e:'I would like to make a hotel reservation for three nights.'},
    {w:'departure',     m:'出發、起飛',   e:'Our departure time has been moved to 8 AM.'},
    {w:'accommodation', m:'住宿',         e:'The conference includes accommodation for two nights.'},
    {w:'layover',       m:'中停、轉機',   e:'We have a two-hour layover in Tokyo.'},
    {w:'complimentary', m:'免費贈送的',   e:'Breakfast is complimentary for all guests.'},
    {w:'cancellation',  m:'取消',         e:'Late cancellation may result in a fee.'},
    {w:'reimbursement', m:'費用報銷',     e:'Submit your receipts for travel reimbursement.'},
    {w:'excess baggage',m:'超重行李',     e:'You may be charged for excess baggage.'},
    {w:'boarding pass', m:'登機證',       e:'Please have your boarding pass ready at the gate.'},
    {w:'amenities',     m:'設施、便利設備',e:'The hotel offers amenities such as a pool and gym.'},
    {w:'round-trip',    m:'來回票',       e:'I would like to book a round-trip ticket to London.'},
    {w:'transit visa',  m:'過境簽證',     e:'You may need a transit visa for the connecting flight.'},
    {w:'check-in',      m:'辦理入住/報到', e:'Online check-in is available 24 hours before departure.'},
    {w:'customs',       m:'海關',         e:'You must declare items worth over $10,000 at customs.'},
    {w:'delay',         m:'延誤、延遲',   e:'The flight was delayed by two hours due to fog.'},
    {w:'confirmation',  m:'確認、訂位確認',e:'Please keep your booking confirmation for reference.'},
    {w:'porter',        m:'行李員',       e:'The porter will take your luggage to the room.'},
    {w:'per diem',      m:'每日津貼',     e:'Employees receive a per diem of $80 for business trips.'},
    {w:'currency exchange',m:'外幣兌換',  e:'Currency exchange is available at the airport.'},
  ],
  patterns:[
    {p:'I would like to + V',         e:'I would like to book a single room for two nights.',         t:'禮貌請求',   tw:'我想要…'},
    {p:'Is there a + N available?',   e:'Is there a direct flight to Paris available on Friday?',     t:'詢問是否有', tw:'請問有…嗎？'},
    {p:'Please be advised that + S+V',e:'Please be advised that check-in begins at 3 PM.',           t:'公告提醒',   tw:'請注意…'},
    {p:'due to + N',                  e:'The flight was delayed due to bad weather conditions.',      t:'原因說明',   tw:'由於…'},
    {p:'We regret to inform you that',e:'We regret to inform you that your flight has been canceled.',t:'遺憾通知',   tw:'我們遺憾地通知您…'},
    {p:'subject to + N',              e:'All reservations are subject to availability.',              t:'視…而定',   tw:'須視…而定'},
    {p:'prior to + N/V-ing',          e:'Please check in prior to the departure time.',              t:'在…之前',   tw:'在…之前'},
    {p:'in the event of + N',         e:'In the event of cancellation, a full refund will be issued.',t:'萬一…',     tw:'萬一發生…'},
  ],
  examTips:[
    'Part 3/4 常考：班機延誤、改期、轉機、飯店 check-in 問題、行程變更',
    'Part 7 常考：行程確認 email、飯店取消政策、旅遊廣告、機票訂購說明',
    'Part 2 常考：詢問航班/訂房狀態、確認時間地點',
    '高頻陷阱：complimentary（免費）≠ complimentary（恭維的）',
    '關鍵字：itinerary / round-trip / one-way / complimentary / amenities / per diem',
    '時態注意：班機時刻表用現在式，延誤通知用被動語態',
  ],
},

// ══════════════════════
//  2. Dining Out 外出用餐篇
// ══════════════════════
{
  id:'dining', icon:'🍽️', name:'Dining Out', nameTw:'外出用餐篇',
  color:'#e8a44a', desc:'餐廳訂位、點餐、外燴、餐飲服務',
  vocab:[
    {w:'reservation',   m:'訂位',          e:'I have a reservation under the name Smith.'},
    {w:'appetizer',     m:'開胃菜',        e:'Would you like to start with an appetizer?'},
    {w:'cuisine',       m:'料理、烹飪風格', e:'The restaurant is known for its French cuisine.'},
    {w:'catering',      m:'外燴服務',      e:'We hired a catering company for the annual event.'},
    {w:'dietary',       m:'飲食的',        e:'Please let us know of any dietary restrictions.'},
    {w:'takeout',       m:'外帶',          e:'Would you prefer dine-in or takeout?'},
    {w:'gratuity',      m:'小費、服務費',   e:'A 15% gratuity is included in the bill.'},
    {w:'specials',      m:'今日特餐',      e:"Today's specials include grilled salmon and risotto."},
    {w:'banquet',       m:'宴席、宴會',    e:'The company dinner will be a banquet-style event.'},
    {w:'buffet',        m:'自助式餐廳',    e:'Lunch will be served buffet style in the main hall.'},
    {w:'entrée',        m:'主菜',          e:'The entrée comes with a choice of soup or salad.'},
    {w:'complimentary', m:'免費贈送的',    e:'Complimentary drinks are served upon arrival.'},
    {w:'vegan',         m:'純素的',        e:'We offer a vegan menu for plant-based diners.'},
    {w:'allergy',       m:'過敏',          e:'Please inform us of any food allergies in advance.'},
    {w:'seating capacity',m:'座位容量',    e:'The banquet hall has a seating capacity of 200.'},
    {w:'private dining', m:'包廂用餐',     e:'A private dining room is available for groups of 10+.'},
    {w:'beverage',      m:'飲料',          e:'All beverages are included in the prix fixe menu.'},
    {w:'prix fixe',     m:'套餐（固定價格）',e:'The prix fixe dinner is $45 per person.'},
    {w:'host',          m:'接待人員、主辦', e:'The host will escort you to your table.'},
    {w:'bill',          m:'帳單',          e:'Could we have the bill, please?'},
  ],
  patterns:[
    {p:"I'd like to reserve a table for + 人數", e:"I'd like to reserve a table for six at 7 PM tonight.",   t:'訂位',       tw:'我想訂…人的位子'},
    {p:'Do you have anything + adj?',            e:'Do you have anything vegetarian on the menu?',            t:'詢問菜單',   tw:'有…的選項嗎？'},
    {p:'Could you accommodate + N?',             e:'Could you accommodate a special dietary request?',        t:'特殊要求',   tw:'能否配合…？'},
    {p:'The set menu includes + N',              e:'The set menu includes three courses and a beverage.',     t:'套餐說明',   tw:'套餐包含…'},
    {p:'We apologize for the wait',              e:'We apologize for the wait and appreciate your patience.', t:'等候致歉',   tw:'為等候時間道歉'},
    {p:'Please inform us in advance if + S+V',  e:'Please inform us in advance if you have any allergies.',  t:'提前告知',   tw:'如有…請提前告知'},
    {p:'A minimum charge of + $ applies',        e:'A minimum charge of $20 per person applies on weekends.', t:'最低消費',   tw:'最低消費為…'},
  ],
  examTips:[
    'Part 2 常考：訂位電話、更改人數、詢問特殊飲食需求',
    'Part 3 常考：餐廳預訂問題、服務投訴、菜單詢問',
    'Part 4 常考：餐廳廣告、外燴服務說明、活動用餐公告',
    'Part 7 常考：餐廳評論、外燴合約、菜單說明',
    '高頻陷阱：gratuity（服務費）通常已包含在帳單內，不需另付',
    '關鍵字：reservation / dietary restriction / complimentary / gratuity / catering',
  ],
},

// ══════════════════════
//  3. Entertainment 娛樂篇
// ══════════════════════
{
  id:'entertainment', icon:'🎭', name:'Entertainment', nameTw:'娛樂篇',
  color:'#9b7fe8', desc:'展覽、表演、活動、票務',
  vocab:[
    {w:'venue',         m:'場地、會場',    e:'The concert venue holds up to 5,000 people.'},
    {w:'admission',     m:'入場費',        e:'Admission is free for children under 12.'},
    {w:'intermission',  m:'中場休息',      e:'There will be a 15-minute intermission after Act 2.'},
    {w:'featured',      m:'特別呈現的',    e:'The film festival featured works by local directors.'},
    {w:'premiere',      m:'首映、首演',    e:'The premiere is scheduled for next Friday evening.'},
    {w:'exhibit',       m:'展覽（品）',    e:'The art exhibit will run through the end of the month.'},
    {w:'ticket stub',   m:'票根',          e:'Please keep your ticket stub for re-entry.'},
    {w:'sold out',      m:'售罄',          e:'The Saturday performance is already sold out.'},
    {w:'box office',    m:'售票處',        e:'Tickets are available at the box office from 10 AM.'},
    {w:'lineup',        m:'陣容、節目表',   e:"This year's festival lineup features 30 performers."},
    {w:'gallery',       m:'藝廊、展覽館',  e:'The gallery is open Tuesday through Sunday.'},
    {w:'curator',       m:'策展人',        e:'The curator will give a guided tour at 2 PM.'},
    {w:'merchandise',   m:'周邊商品',      e:'Official merchandise is available at the gift shop.'},
    {w:'backstage',     m:'後台',          e:'VIP ticket holders can access the backstage area.'},
    {w:'matinee',       m:'日場演出',      e:'Matinee tickets are discounted by 20%.'},
    {w:'standing ovation',m:'起立鼓掌',   e:'The performance received a standing ovation.'},
    {w:'opening night', m:'首演之夜',      e:'Opening night tickets are nearly sold out.'},
    {w:'ensemble',      m:'劇團、合奏團',  e:'The ensemble has been performing for over 20 years.'},
    {w:'rehearsal',     m:'排練、彩排',    e:'The dress rehearsal is scheduled for Thursday.'},
    {w:'program',       m:'節目單',        e:'A program is included with each ticket purchase.'},
  ],
  patterns:[
    {p:'Tickets are available + 地點/方式',    e:'Tickets are available online or at the door on the night.',        t:'售票資訊', tw:'票券可在…購得'},
    {p:'The event will be held + 時地',        e:'The event will be held at the Grand Theater on March 15th.',       t:'活動舉行', tw:'活動將於…舉行'},
    {p:'For more information, + V',            e:'For more information, please visit our official website.',         t:'更多資訊', tw:'更多資訊請…'},
    {p:'Seating is on a first-come basis',     e:'Seating for the free event is on a first-come, first-served basis.',t:'先到先得',tw:'座位採先到先得'},
    {p:'A + adj + experience awaits',          e:'An unforgettable musical experience awaits all attendees.',        t:'宣傳語',   tw:'…體驗等待著您'},
    {p:'In the event of cancellation, + S+V',  e:'In the event of cancellation, ticket holders will be refunded.',  t:'取消政策', tw:'若活動取消…'},
    {p:'Doors open at + 時間',                 e:'Doors open at 7:00 PM, one hour before the show.',                t:'開門時間', tw:'大門於…開放'},
  ],
  examTips:[
    'Part 4 常考：廣播節目介紹、表演廣告、活動公告',
    'Part 7 常考：活動公告、展覽說明、票務規則、評論',
    'Part 2 常考：詢問票務、演出時間、場地位置',
    '高頻題型：Look at the graphic（時間表/節目單）整合題',
    '關鍵字：admission / venue / sold out / intermission / box office / matinee',
    '注意：sold out（售罄）= no longer available 是常考同義替換',
  ],
},

// ══════════════════════
//  4. Housing 房屋篇
// ══════════════════════
{
  id:'housing', icon:'🏠', name:'Housing', nameTw:'房屋篇',
  color:'#4caf82', desc:'租屋、買賣、維修、物業管理',
  vocab:[
    {w:'lease',         m:'租約、租賃',    e:'The lease agreement is for one year with an option to renew.'},
    {w:'landlord',      m:'房東',          e:'The landlord agreed to repaint the apartment before move-in.'},
    {w:'deposit',       m:'押金、定金',    e:'A security deposit equal to one month rent is required.'},
    {w:'utilities',     m:'水電費',        e:'Utilities are not included in the monthly rent.'},
    {w:'renovation',    m:'整修、翻新',    e:'The building is undergoing major renovation this summer.'},
    {w:'property',      m:'房產、物業',    e:'The company owns several commercial properties downtown.'},
    {w:'mortgage',      m:'抵押貸款',      e:'They applied for a 30-year mortgage at a fixed rate.'},
    {w:'tenant',        m:'承租人、房客',   e:'The tenant is responsible for minor repairs under $100.'},
    {w:'vacancy',       m:'空缺、空屋',    e:'There are currently two vacancies in the building.'},
    {w:'maintenance',   m:'維護、保養',    e:'Report any maintenance issues to the building manager.'},
    {w:'sublease',      m:'轉租',          e:'Subleasing is not permitted without written approval.'},
    {w:'real estate',   m:'不動產',        e:'She works as a real estate agent in the downtown area.'},
    {w:'appraisal',     m:'估價',          e:'An independent appraisal determined the property value.'},
    {w:'zoning',        m:'分區規劃',      e:'The area is zoned for residential use only.'},
    {w:'homeowner',     m:'房屋所有人',    e:'Homeowners are responsible for their own property taxes.'},
    {w:'property tax',  m:'房產稅',        e:'Property taxes are paid annually to the local government.'},
    {w:'eviction',      m:'驅逐、驅離',   e:'The landlord filed for eviction due to unpaid rent.'},
    {w:'condominium',   m:'公寓大廈',      e:'She purchased a condominium on the 15th floor.'},
    {w:'association fee',m:'管理費',       e:'The monthly association fee covers building maintenance.'},
    {w:'floor plan',    m:'平面圖',        e:'Could you send me the floor plan for the unit?'},
  ],
  patterns:[
    {p:'The rent is + $ per month',          e:'The rent is $1,500 per month, utilities included.',           t:'租金說明',  tw:'租金為…'},
    {p:'Subject to + N',                     e:'All renovations are subject to management approval.',          t:'需經審核',  tw:'需視…而定'},
    {p:'Effective + date',                   e:'The new lease terms are effective January 1st.',              t:'生效日期',  tw:'自…起生效'},
    {p:'The tenant is responsible for + N',  e:'The tenant is responsible for maintaining the garden.',       t:'責任歸屬',  tw:'承租人須負責…'},
    {p:'Prior written notice of + 天數 days',e:'Prior written notice of 30 days is required to terminate.',  t:'提前通知',  tw:'需提前…天書面通知'},
    {p:'The property will be available + 時間',e:'The property will be available for occupancy on March 1st.',t:'入住時間', tw:'物件…可入住'},
    {p:'In case of + N, contact + 人',       e:'In case of emergency, contact the building manager directly.',t:'緊急聯絡', tw:'如遇…請聯絡…'},
    {p:'Failure to + V will result in + N',  e:'Failure to pay rent on time will result in a late fee.',      t:'違約後果',  tw:'未能…將導致…'},
  ],
  examTips:[
    'Part 3 常考：房客與房東的溝通、維修請求、合約問題',
    'Part 7 常考：租約條款、維修通知、公寓廣告、物業管理公告',
    'Part 4 常考：大樓停車場、設施維修、公告',
    '高頻陷阱：deposit（押金）≠ monthly rent，不要搞混',
    '關鍵字：lease / deposit / utilities / tenant / maintenance / sublease',
    '注意：lease（名詞=租約，動詞=出租/承租），rent（名詞=租金，動詞=租）',
  ],
},

// ══════════════════════
//  5. Purchasing 採購篇
// ══════════════════════
{
  id:'purchasing', icon:'🛒', name:'Purchasing', nameTw:'採購篇',
  color:'#e05c5c', desc:'訂購、議價、供應商、付款條件',
  vocab:[
    {w:'invoice',        m:'發票、帳單',   e:'Please send the invoice to our accounting department.'},
    {w:'purchase order', m:'採購訂單',     e:'A purchase order must be approved before placing the order.'},
    {w:'vendor',         m:'供應商',       e:'We are comparing quotes from three different vendors.'},
    {w:'bulk discount',  m:'批量折扣',     e:'A bulk discount is available for orders over 500 units.'},
    {w:'backorder',      m:'延期交貨訂單', e:'The item is on backorder and will ship in two weeks.'},
    {w:'quote',          m:'報價',         e:'Could you send us a quote for 200 units?'},
    {w:'warranty',       m:'保固',         e:'The product comes with a one-year warranty.'},
    {w:'defective',      m:'有缺陷的',     e:'We received a shipment of defective parts last week.'},
    {w:'procurement',    m:'採購（正式）',  e:'Our procurement team handles all supplier contracts.'},
    {w:'net 30',         m:'30天付款條件', e:'Payment terms are net 30 from the invoice date.'},
    {w:'lead time',      m:'前置時間',     e:'The lead time for custom orders is six weeks.'},
    {w:'RFQ',            m:'詢價單',       e:'We sent out an RFQ to five potential suppliers.'},
    {w:'inventory',      m:'庫存',         e:'Current inventory levels are sufficient for two months.'},
    {w:'wholesale',      m:'批發',         e:'Wholesale prices are available for orders over 1,000 units.'},
    {w:'consignment',    m:'寄售',         e:'Goods are delivered on consignment and paid after sale.'},
    {w:'price negotiation',m:'議價',       e:'Price negotiation is expected for large volume orders.'},
    {w:'compliance',     m:'遵守規定',     e:'All vendors must demonstrate regulatory compliance.'},
    {w:'freight',        m:'貨運費',       e:'Freight costs are included in the quoted price.'},
    {w:'COD',            m:'貨到付款',     e:'Small orders may be placed on a COD basis.'},
    {w:'return policy',  m:'退貨政策',     e:'Our return policy allows returns within 30 days of delivery.'},
  ],
  patterns:[
    {p:'We would like to place an order for + N',e:'We would like to place an order for 300 units of item #A201.',t:'下訂單',   tw:'我們想訂購…'},
    {p:'Could you provide a quote for + N?',     e:'Could you provide a quote for bulk printing of 5,000 copies?', t:'詢價',     tw:'能否提供…的報價？'},
    {p:'The shipment is scheduled for + date',   e:'The shipment is scheduled for delivery on Friday, March 10.',  t:'出貨說明', tw:'貨物預計於…出貨'},
    {p:'Please confirm receipt of + N',          e:'Please confirm receipt of this purchase order by end of day.',  t:'確認收到', tw:'請確認已收到…'},
    {p:'We reserve the right to + V',            e:'We reserve the right to cancel orders in case of non-payment.',t:'保留權利', tw:'我們保留…的權利'},
    {p:'Payment is due within + N days of + N',  e:'Payment is due within 30 days of invoice receipt.',           t:'付款期限', tw:'付款期限為…天內'},
    {p:'A restocking fee of + % applies',        e:'A restocking fee of 15% applies to all returned merchandise.', t:'補貨費',   tw:'退貨須支付…%的補貨費'},
  ],
  examTips:[
    'Part 7 常考：採購 email、發票、訂單確認、供應商合約',
    'Part 3 常考：採購部門對話、供應商協商、訂單問題',
    'Part 5 常考：採購相關詞彙的詞性和介系詞搭配',
    '高頻題型：雙篇/三篇文章（採購訂單 + 回覆 email）',
    '關鍵字：invoice / purchase order / vendor / backorder / net 30 / lead time',
    '注意：quote（報價）= estimate；invoice（帳單）在交易後才開立',
  ],
},

// ══════════════════════
//  6. Personnel 人事篇
// ══════════════════════
{
  id:'personnel', icon:'👥', name:'Personnel', nameTw:'人事篇',
  color:'#5b8fd4', desc:'招聘、面試、升遷、績效評估',
  vocab:[
    {w:'recruitment',    m:'招聘',          e:'The recruitment process takes about four weeks.'},
    {w:'applicant',      m:'求職者、申請人', e:'We received over 200 applicants for the position.'},
    {w:'resume/CV',      m:'履歷',          e:'Please submit your resume and a cover letter.'},
    {w:'probation',      m:'試用期',        e:'New employees undergo a 90-day probation period.'},
    {w:'performance review',m:'績效評估',   e:'Annual performance reviews are held in December.'},
    {w:'promotion',      m:'晉升',          e:'She received a promotion to Senior Manager last month.'},
    {w:'severance',      m:'資遣費',        e:'Laid-off employees will receive severance packages.'},
    {w:'payroll',        m:'薪資發放',      e:'The payroll department handles all salary processing.'},
    {w:'incentive',      m:'獎勵、激勵',    e:'Sales staff receive a quarterly incentive bonus.'},
    {w:'onboarding',     m:'新人培訓流程',  e:'Our onboarding program lasts two weeks.'},
    {w:'reference',      m:'推薦人、推薦信', e:'Please provide two professional references.'},
    {w:'compensation',   m:'薪酬、補償',    e:'Compensation includes salary, bonus, and benefits.'},
    {w:'termination',    m:'終止（合約/職務）',e:'Termination of employment requires two weeks notice.'},
    {w:'intern',         m:'實習生',        e:'We hire ten interns every summer semester.'},
    {w:'headhunter',     m:'獵人頭',        e:'The position was filled through a headhunter firm.'},
    {w:'overtime',       m:'加班',          e:'Overtime pay is 1.5 times the regular hourly rate.'},
    {w:'benefits',       m:'福利',          e:'Benefits include health insurance and a retirement plan.'},
    {w:'workforce',      m:'勞動力、員工總數',e:'The company expanded its workforce by 200 employees.'},
    {w:'resignation',    m:'辭職',          e:'Her resignation took effect at the end of the month.'},
    {w:'job description',m:'職位說明',      e:'Please review the job description before applying.'},
  ],
  patterns:[
    {p:'We are looking for candidates with + N', e:'We are looking for candidates with five years of relevant experience.',t:'徵才條件',tw:'我們尋找具備…的人才'},
    {p:'The position requires + N/V-ing',        e:'The position requires fluency in English and Mandarin.',              t:'職位要求',tw:'此職位需要…'},
    {p:'We are pleased to offer you + N',        e:'We are pleased to offer you the position of Marketing Manager.',      t:'錄取通知',tw:'我們很高興提供您…職位'},
    {p:'Salary is commensurate with + N',        e:'Salary is commensurate with experience and qualifications.',         t:'薪資說明',tw:'薪資依…而定'},
    {p:'Qualified candidates should + V',        e:'Qualified candidates should submit applications by March 31st.',      t:'應徵說明',tw:'符合資格的應徵者應…'},
    {p:'Following a review of + N, we + V',      e:'Following a review of your application, we would like to interview you.',t:'邀請面試',tw:'審核…後，我們…'},
    {p:'Effective + date, + S+V',                e:'Effective January 1st, the new HR policy will be in place.',         t:'生效公告',tw:'自…起，…'},
  ],
  examTips:[
    'Part 7 常考：職缺廣告、錄取通知、績效評估表、離職信',
    'Part 3 常考：面試情景、升遷/調職通知、績效討論',
    'Part 4 常考：公司公告（人事異動）、歡迎新員工',
    'Part 5 常考：人事詞彙的詞性（recruit/recruitment/recruiter）',
    '高頻題型：Who most likely is the speaker? = 判斷說話者身份',
    '關鍵字：recruitment / probation / performance review / onboarding / compensation',
  ],
},

// ══════════════════════
//  7. Offices 辦公室篇
// ══════════════════════
{
  id:'offices', icon:'🏢', name:'Offices', nameTw:'辦公室篇',
  color:'#e8b86d', desc:'辦公設備、會議、行政、文件處理',
  vocab:[
    {w:'agenda',          m:'議程',          e:'Please review the agenda before the meeting.'},
    {w:'minutes',         m:'會議記錄',      e:'Sarah will take the minutes during the meeting.'},
    {w:'memo',            m:'備忘錄',        e:'A memo was sent to all staff about the policy change.'},
    {w:'deadline',        m:'截止日期',      e:'The report deadline is this Friday at 5 PM.'},
    {w:'cc',              m:'副本（電郵）',  e:'Please cc the finance department on this email.'},
    {w:'conference call', m:'電話會議',      e:'We will have a conference call with the Tokyo office.'},
    {w:'workload',        m:'工作量',        e:'The new hire will help reduce our workload significantly.'},
    {w:'cubicle',         m:'隔間辦公桌',   e:'Each employee has their own cubicle on the third floor.'},
    {w:'copier',          m:'影印機',        e:'The copier on the third floor is currently out of order.'},
    {w:'delegate',        m:'委派工作',      e:'The manager delegated the task to her assistant.'},
    {w:'telecommute',     m:'遠距辦公',      e:'Employees may telecommute up to two days per week.'},
    {w:'stationery',      m:'文具',          e:'Office stationery can be ordered through the supply portal.'},
    {w:'projector',       m:'投影機',        e:'Please set up the projector before the presentation.'},
    {w:'workflow',        m:'工作流程',      e:'We are looking for ways to streamline the workflow.'},
    {w:'filing',          m:'歸檔',          e:'Electronic filing has replaced most paper-based systems.'},
    {w:'out of office',   m:'外出/不在辦公室',e:'I will be out of office from March 10–15.'},
    {w:'archive',         m:'封存、資料庫',  e:'Please archive completed project files in the shared drive.'},
    {w:'receptionist',    m:'接待人員',      e:'The receptionist will direct visitors to the meeting room.'},
    {w:'initiative',      m:'主動、新計畫',  e:'The office recycling initiative was very successful.'},
    {w:'circulation',     m:'流傳、發行',    e:'Please limit internal email circulation to relevant staff.'},
  ],
  patterns:[
    {p:'The meeting is scheduled for + 時間',    e:'The meeting is scheduled for 2 PM in Conference Room B.',            t:'會議安排',  tw:'會議安排於…'},
    {p:'Please ensure that + S+V',               e:'Please ensure that all reports are submitted by end of day Friday.',   t:'確認事項',  tw:'請確保…'},
    {p:'I am writing to + V',                    e:'I am writing to inform you of a schedule change for next week.',       t:'電郵開頭',  tw:'我寫信是為了…'},
    {p:'As a reminder, + S+V',                   e:'As a reminder, the office will be closed on Monday.',                  t:'提醒事項',  tw:'提醒您…'},
    {p:'Please be aware that + S+V',             e:'Please be aware that the server will be down for maintenance tonight.',t:'注意事項',  tw:'請注意…'},
    {p:'Going forward, + S+V',                   e:'Going forward, all requests must be submitted through the new system.',t:'今後方針',  tw:'今後…'},
    {p:'Kindly + V by + 時間',                   e:'Kindly return the signed form by this Friday.',                       t:'禮貌請求',  tw:'煩請於…前…'},
    {p:'For your reference, + S+V',              e:'For your reference, the updated policy is attached.',                  t:'供參考',    tw:'供您參考…'},
  ],
  examTips:[
    'Part 3 常考：會議安排、工作分配、設備故障、電話留言',
    'Part 6/7 常考：備忘錄、內部公告、電子郵件、政策說明',
    'Part 2 常考：確認會議時間地點、詢問任務分配',
    '高頻文體：memo（備忘錄）格式：To / From / Date / Re / Subject',
    '關鍵字：agenda / minutes / deadline / cc / delegate / telecommute',
    '注意：cc（Carbon Copy）= 副本，bcc = 密件副本',
  ],
},

// ══════════════════════
//  8. Health 健康篇
// ══════════════════════
{
  id:'health', icon:'🏥', name:'Health', nameTw:'健康篇',
  color:'#4caf82', desc:'醫療保險、預約、職場健康',
  vocab:[
    {w:'prescription',   m:'處方箋',        e:'You need a prescription for this medication.'},
    {w:'insurance',      m:'保險',          e:'Our company provides full health insurance coverage.'},
    {w:'coverage',       m:'保險範圍、涵蓋', e:'Does your insurance coverage include dental?'},
    {w:'deductible',     m:'自付額（保險）', e:'The annual deductible is $500 per person.'},
    {w:'specialist',     m:'專科醫師',      e:'Your doctor referred you to a cardiologist specialist.'},
    {w:'wellness',       m:'健康促進',      e:'The company offers a wellness program for all employees.'},
    {w:'pharmacy',       m:'藥局',          e:'The prescription can be filled at any participating pharmacy.'},
    {w:'symptoms',       m:'症狀',          e:'Please describe your symptoms to the nurse first.'},
    {w:'checkup',        m:'健康檢查',      e:'Annual checkups are covered by the insurance plan.'},
    {w:'ergonomic',      m:'符合人體工學的', e:'We provide ergonomic chairs and desks for all staff.'},
    {w:'copayment',      m:'部分自付額',    e:'There is a $20 copayment for each doctor visit.'},
    {w:'out-of-network', m:'非網絡內（保險）',e:'Out-of-network visits are only partially covered.'},
    {w:'premium',        m:'保險費',        e:'The monthly premium is deducted directly from payroll.'},
    {w:'referral',       m:'轉介、轉診',    e:'You need a referral to see a specialist.'},
    {w:'sick leave',     m:'病假',          e:'Full-time employees receive 10 days of paid sick leave.'},
    {w:'occupational',   m:'職業的、職場的', e:'Occupational hazards must be reported to HR immediately.'},
    {w:'EAP',            m:'員工協助計畫',  e:'Our EAP offers free counseling sessions for employees.'},
    {w:'generic',        m:'學名藥',        e:'Ask your pharmacist about a generic alternative to reduce cost.'},
    {w:'pre-existing',   m:'既往症',        e:'Pre-existing conditions may affect your coverage.'},
    {w:'claim',          m:'保險申請',      e:'Submit your medical receipts to file an insurance claim.'},
  ],
  patterns:[
    {p:"I'd like to make an appointment with + 醫師", e:"I'd like to make an appointment with Dr. Lee for Monday afternoon.",t:'預約看診', tw:'我想預約…醫師'},
    {p:'Your insurance covers + N',                   e:'Your insurance covers up to $200 annually for eyewear.',           t:'保險說明', tw:'你的保險涵蓋…'},
    {p:'Please contact + 部門 + regarding + N',       e:'Please contact HR regarding your health insurance benefits.',       t:'聯絡指引', tw:'請聯絡…關於…'},
    {p:'Coverage is provided for + N',                e:'Coverage is provided for preventive care and annual checkups.',     t:'涵蓋範圍', tw:'保險涵蓋…'},
    {p:'A copayment of + $ is required for + N',      e:'A copayment of $30 is required for specialist visits.',            t:'自付說明', tw:'…需支付$…自付額'},
    {p:'Employees are eligible for + N after + N',    e:'Employees are eligible for dental benefits after 90 days.',        t:'福利資格', tw:'員工在…後有資格享有…'},
    {p:'In case of emergency, proceed to + 地點',     e:'In case of emergency, proceed to the nearest urgent care center.',  t:'緊急處置', tw:'緊急情況請前往…'},
  ],
  examTips:[
    'Part 7 常考：保險說明書、醫療福利公告、診所廣告',
    'Part 3 常考：員工請病假、保險問題詢問',
    'Part 4 常考：健康計畫公告、醫療保險說明',
    '高頻陷阱：coverage（名詞）≠ cover（動詞），注意詞性',
    '關鍵字：insurance / coverage / deductible / prescription / wellness / copayment',
    '注意：premium（保費）/ deductible（自付額）/ copayment（就診自付）是三個不同概念',
  ],
},

// ══════════════════════
//  9. General Business 一般商務篇
// ══════════════════════
{
  id:'general_biz', icon:'💼', name:'General Business', nameTw:'一般商務篇',
  color:'#5b8fd4', desc:'商務往來、合作、策略、簡報',
  vocab:[
    {w:'proposal',       m:'提案、企劃書',  e:'We submitted a proposal to the client last week.'},
    {w:'objective',      m:'目標',          e:'The main objective is to increase market share by 10%.'},
    {w:'strategy',       m:'策略',          e:'The team developed a new marketing strategy for Q4.'},
    {w:'stakeholder',    m:'利害關係人',    e:'All stakeholders were invited to the presentation.'},
    {w:'revenue',        m:'營收',          e:'Revenue increased by 15% in the third quarter.'},
    {w:'contract',       m:'合約',          e:'Both parties signed the contract yesterday morning.'},
    {w:'benchmark',      m:'基準、標竿',    e:'We use industry benchmarks to evaluate our performance.'},
    {w:'fiscal year',    m:'財政年度',      e:'Our fiscal year ends on March 31st.'},
    {w:'collaborate',    m:'合作',          e:'We will collaborate with a local firm on this project.'},
    {w:'initiative',     m:'主動、新計畫',  e:'The company launched a new sustainability initiative.'},
    {w:'feasibility',    m:'可行性',        e:'A feasibility study was conducted before the project.'},
    {w:'ROI',            m:'投資報酬率',    e:'The campaign delivered an ROI of 200%.'},
    {w:'briefing',       m:'簡報、情況說明', e:'The client briefing is scheduled for Tuesday morning.'},
    {w:'counterpart',    m:'對應的人/機構', e:'I will meet with my counterpart from the Paris office.'},
    {w:'market share',   m:'市場份額',      e:'Our goal is to capture 20% of the market share.'},
    {w:'due diligence',  m:'盡職調查',      e:'Due diligence was completed before signing the agreement.'},
    {w:'agenda',         m:'議程、目標',    e:'What is on the agenda for this quarter?'},
    {w:'networking',     m:'建立人脈',      e:'The conference is a great opportunity for networking.'},
    {w:'clause',         m:'條款',          e:'Please review the confidentiality clause in the contract.'},
    {w:'subsidiary',     m:'子公司',        e:'The subsidiary operates independently in Southeast Asia.'},
  ],
  patterns:[
    {p:'We are pleased to announce + N/that',    e:'We are pleased to announce the launch of our new product line.',   t:'公告喜訊', tw:'我們很高興宣布…'},
    {p:'As per + N',                             e:'As per our agreement, payment is due within 30 days.',             t:'根據…',    tw:'根據我們的…'},
    {p:'We look forward to + V-ing',             e:'We look forward to a long and productive partnership.',            t:'期待合作', tw:'我們期待…'},
    {p:'This is to confirm that + S+V',          e:'This is to confirm that the meeting has been rescheduled.',        t:'確認事項', tw:'特此確認…'},
    {p:'Please find attached + N',               e:'Please find attached the signed contract for your review.',        t:'附件說明', tw:'附件請見…'},
    {p:'Should you have any questions, + V',     e:'Should you have any questions, please do not hesitate to contact us.',t:'詢問邀請',tw:'如有任何問題，請…'},
    {p:'We would appreciate it if + S+V',        e:'We would appreciate it if you could reply by end of this week.',   t:'禮貌請求', tw:'如您能…，我們將不勝感激'},
    {p:'In accordance with + N',                 e:'In accordance with our policy, all returns must be approved.',     t:'依照…',    tw:'依照…'},
  ],
  examTips:[
    'Part 7 常考：商務提案、合約條款、業績報告、商務 email',
    'Part 5 常考：商務詞彙的詞性、固定搭配介系詞',
    'Part 3/4 常考：會議簡報、客戶接待、業績報告',
    '高頻文體：email 開頭和結尾的固定用語',
    '關鍵字：proposal / revenue / stakeholder / fiscal year / initiative / ROI',
    '注意：as per（根據）= according to，正式商務用語',
  ],
},

// ══════════════════════
//  10. Manufacturing 製造業篇
// ══════════════════════
{
  id:'manufacturing', icon:'🏭', name:'Manufacturing', nameTw:'製造業篇',
  color:'#9b7fe8', desc:'生產流程、品管、出貨、工廠作業',
  vocab:[
    {w:'assembly line',  m:'生產線',        e:'The assembly line operates 24 hours a day, 7 days a week.'},
    {w:'defective',      m:'有缺陷的',      e:'Defective products are removed from the production line.'},
    {w:'quality control',m:'品質管制',      e:'Our quality control team inspects every production batch.'},
    {w:'output',         m:'產量',          e:'We aim to increase output by 20% this quarter.'},
    {w:'raw material',   m:'原物料',        e:'Rising costs of raw materials affect our profit margins.'},
    {w:'shipment',       m:'貨運批次',      e:'The shipment arrived two days ahead of schedule.'},
    {w:'inventory',      m:'庫存',          e:'We need to conduct a full inventory count this weekend.'},
    {w:'compliance',     m:'法規遵守',      e:'The factory must maintain compliance with all safety regulations.'},
    {w:'prototype',      m:'原型、樣品',    e:'Engineers are currently testing the new prototype.'},
    {w:'throughput',     m:'生產量、吞吐量', e:'We improved throughput by optimizing the workflow.'},
    {w:'yield',          m:'產出率',        e:'The yield rate improved from 92% to 97% after adjustments.'},
    {w:'downtime',       m:'停機時間',      e:'Unexpected downtime costs the company $5,000 per hour.'},
    {w:'specifications', m:'規格、規格書',  e:'Products must meet all customer specifications.'},
    {w:'foreman',        m:'領班、工頭',    e:'The foreman is responsible for supervising the production team.'},
    {w:'safety regulations',m:'安全規定',   e:'All workers must follow safety regulations at all times.'},
    {w:'vendor',         m:'供應商',        e:'We are evaluating three vendors for component supply.'},
    {w:'load capacity',  m:'承載量',        e:'The conveyor belt has a maximum load capacity of 500 kg.'},
    {w:'calibrate',      m:'校準',          e:'Equipment must be calibrated at the start of each shift.'},
    {w:'batch',          m:'批次',          e:'Each batch is tested before being released for shipment.'},
    {w:'recall',         m:'召回',          e:'The company issued a voluntary recall of affected products.'},
  ],
  patterns:[
    {p:'The production of + N has been + adj',     e:'The production of the new model has been temporarily delayed.',       t:'生產狀況說明',tw:'…的生產已…'},
    {p:'In order to + V',                          e:'In order to meet demand, we increased production hours this week.',    t:'目的說明',    tw:'為了…'},
    {p:'All products must + V',                    e:'All products must pass a safety inspection before shipping.',          t:'規定要求',    tw:'所有產品必須…'},
    {p:'The factory will be shut down for + N',    e:'The factory will be shut down for scheduled maintenance next Monday.', t:'停工公告',    tw:'工廠將因…停工'},
    {p:'Workers are required to + V',              e:'Workers are required to wear protective gear at all times.',           t:'工作規定',    tw:'員工須…'},
    {p:'Due to a shortage of + N, + S+V',          e:'Due to a shortage of components, production has been reduced.',        t:'短缺說明',    tw:'由於…短缺，…'},
    {p:'We have implemented + N to improve + N',   e:'We have implemented new processes to improve product quality.',        t:'改善措施',    tw:'我們已實施…以改善…'},
  ],
  examTips:[
    'Part 4 常考：工廠公告、安全說明、生產進度、停工通知',
    'Part 7 常考：品管報告、出貨通知、製程說明、召回公告',
    'Part 3 常考：生產線問題討論、供應商協商',
    '高頻題型：圖表題（生產數量/良率圖）',
    '關鍵字：assembly line / quality control / defective / inventory / compliance / recall',
    '注意：recall（動詞=召回）= Product Recall Notice 是重要文體',
  ],
},

// ══════════════════════
//  11. Corporate Development 企業發展篇
// ══════════════════════
{
  id:'corporate', icon:'📈', name:'Corporate Development', nameTw:'企業發展篇',
  color:'#e8b86d', desc:'合併收購、企業策略、組織變革',
  vocab:[
    {w:'merger',          m:'合併',          e:'The merger was approved by shareholders last month.'},
    {w:'acquisition',     m:'收購',          e:'The company announced the acquisition of a startup.'},
    {w:'restructuring',   m:'重組',          e:'The restructuring plan will reduce costs significantly.'},
    {w:'subsidiary',      m:'子公司',        e:'They opened a wholly-owned subsidiary in Singapore.'},
    {w:'shareholder',     m:'股東',          e:'Shareholders will vote on the merger next week.'},
    {w:'board of directors',m:'董事會',      e:'The board of directors approved the new strategy unanimously.'},
    {w:'expansion',       m:'擴張',          e:"The company's expansion into Asia has been successful."},
    {w:'downsizing',      m:'裁員、縮編',    e:'Downsizing affected 200 employees across three departments.'},
    {w:'headquarters',    m:'總部',          e:'The headquarters will relocate to New York next year.'},
    {w:'stock',           m:'股票',          e:"The company's stock rose 5% after the announcement."},
    {w:'joint venture',   m:'合資企業',      e:'The two companies formed a joint venture in Vietnam.'},
    {w:'due diligence',   m:'盡職調查',      e:'Due diligence is required before any major acquisition.'},
    {w:'equity',          m:'股東權益',      e:'The startup raised $5M through equity financing.'},
    {w:'IPO',             m:'首次公開募股',  e:'The company plans an IPO on the New York Stock Exchange.'},
    {w:'franchise',       m:'特許經營',      e:'The brand expanded through a franchise model.'},
    {w:'liquidation',     m:'清算',          e:'The failing company went into liquidation last quarter.'},
    {w:'takeover',        m:'接管、收購',    e:'The hostile takeover attempt was rejected by the board.'},
    {w:'annual report',   m:'年報',          e:'The annual report highlights record-breaking revenue.'},
    {w:'brand equity',    m:'品牌價值',      e:'Years of quality service have built strong brand equity.'},
    {w:'spin-off',        m:'分拆子公司',    e:'The IT division was spun off as an independent company.'},
  ],
  patterns:[
    {p:'Following the + N',                      e:'Following the merger, all employees will be transferred to the new entity.',t:'合併後',     tw:'在…之後'},
    {p:'The company plans to + V',               e:'The company plans to expand operations into three new markets.',            t:'企業計畫',   tw:'公司計畫…'},
    {p:'Effective immediately, + S+V',           e:'Effective immediately, all travel requests must be pre-approved.',         t:'立即生效',   tw:'即日起…'},
    {p:'As part of the + N, + S+V',              e:'As part of the restructuring, two departments will be merged.',            t:'重組說明',   tw:'作為…的一部分…'},
    {p:'The board has voted to + V',             e:'The board has voted to approve the acquisition of XYZ Corp.',             t:'董事會決議', tw:'董事會投票決定…'},
    {p:'In an effort to + V, + S+V',             e:'In an effort to cut costs, the company is reducing its workforce.',        t:'努力目標',   tw:'為了…，…'},
    {p:'Shareholders are advised that + S+V',    e:'Shareholders are advised that dividends will be increased this year.',     t:'股東通知',   tw:'建議股東注意…'},
    {p:'The transition is expected to + V',      e:'The transition is expected to be completed by end of Q2.',                 t:'過渡期',     tw:'過渡期預計…'},
  ],
  examTips:[
    'Part 4 常考：公司公告（合併/重組/遷址）、員工大會宣布',
    'Part 7 常考：股東信、年報摘要、合併說明、新聞稿',
    'Part 3 常考：主管間討論策略、告知部門變動',
    '高頻文體：press release（新聞稿）格式和用語',
    '關鍵字：merger / acquisition / restructuring / subsidiary / shareholder / joint venture',
    '注意：merger（雙方合併）≠ acquisition（一方收購另一方）',
  ],
},

// ══════════════════════
//  12. Technical Areas 技術層面篇
// ══════════════════════
{
  id:'technical', icon:'💻', name:'Technical Areas', nameTw:'技術層面篇',
  color:'#5b8fd4', desc:'IT、工程、技術支援、系統操作',
  vocab:[
    {w:'software',        m:'軟體',          e:'The new software update will be released next week.'},
    {w:'troubleshoot',    m:'排除故障',      e:'Our IT team will troubleshoot the network issue.'},
    {w:'install',         m:'安裝',          e:'Please install the latest version of the application.'},
    {w:'upgrade',         m:'升級',          e:'All computers will be upgraded to the new operating system.'},
    {w:'bandwidth',       m:'頻寬',          e:'We need more bandwidth to support remote work.'},
    {w:'firewall',        m:'防火牆',        e:'The firewall successfully blocked unauthorized access.'},
    {w:'backup',          m:'備份',          e:'Data backup is performed automatically every night.'},
    {w:'database',        m:'資料庫',        e:'The database stores all customer records and order history.'},
    {w:'server',          m:'伺服器',        e:'The server went down for scheduled maintenance last night.'},
    {w:'glitch',          m:'小故障、異常',  e:'There was a minor glitch in the payment system.'},
    {w:'cybersecurity',   m:'網路安全',      e:'Cybersecurity training is mandatory for all employees.'},
    {w:'encryption',      m:'加密',          e:'All sensitive data is protected by encryption.'},
    {w:'cloud',           m:'雲端',          e:'We migrated all data to cloud storage last year.'},
    {w:'IT infrastructure',m:'IT 基礎設施',  e:'Upgrading the IT infrastructure will cost $2 million.'},
    {w:'patch',           m:'修補程式',      e:'Apply the security patch immediately to prevent vulnerabilities.'},
    {w:'interface',       m:'介面',          e:'The new user interface is much more intuitive.'},
    {w:'downtime',        m:'系統停機時間',  e:'The scheduled downtime will last approximately two hours.'},
    {w:'configuration',   m:'組態設定',      e:'The system configuration was changed by the IT team.'},
    {w:'log in / log out',m:'登入/登出',     e:'Please log out of all systems before leaving the office.'},
    {w:'data breach',     m:'資料外洩',      e:'The company reported a data breach affecting 10,000 users.'},
  ],
  patterns:[
    {p:'The system will be + adj + for + 時間',    e:'The system will be unavailable for approximately two hours.',            t:'系統維護說明',tw:'系統將…'},
    {p:'If you experience + N, please + V',        e:'If you experience any login issues, please contact IT support.',         t:'問題處理指引',tw:'如果你遇到…，請…'},
    {p:'We apologize for any + N + caused by + N', e:'We apologize for any inconvenience caused by the system outage.',        t:'道歉說明',    tw:'為…造成的…致歉'},
    {p:'Users are advised to + V',                 e:'Users are advised to change their passwords immediately.',               t:'使用者提醒',  tw:'使用者應…'},
    {p:'The issue has been resolved and + S+V',    e:'The issue has been resolved and all systems are fully operational.',     t:'問題解決公告',tw:'問題已解決，…'},
    {p:'To ensure + N, please + V',                e:'To ensure data security, please enable two-factor authentication.',      t:'確保安全',    tw:'為確保…，請…'},
    {p:'Access to + N will be restricted + 時間',  e:'Access to the network will be restricted during the upgrade.',           t:'存取限制',    tw:'…期間，對…的存取將受限制'},
  ],
  examTips:[
    'Part 4 常考：系統維護公告、IT 變更通知、網路中斷說明',
    'Part 7 常考：技術手冊摘要、IT 支援 email、系統更新公告',
    'Part 3 常考：技術問題討論、IT 支援通話',
    '高頻題型：What will happen to users during the maintenance? = 後續行動題',
    '關鍵字：troubleshoot / upgrade / backup / server / glitch / cybersecurity / downtime',
    '注意：downtime（技術）= 系統停機；在其他情境可能 = 空閒時間',
  ],
},

// ══════════════════════
//  13. Financing 財務金融篇
// ══════════════════════
{
  id:'financing', icon:'💰', name:'Financing', nameTw:'財務金融篇',
  color:'#4caf82', desc:'財報、預算、投資、貸款、會計',
  vocab:[
    {w:'budget',          m:'預算',          e:'The annual budget was approved by the board of directors.'},
    {w:'expenditure',     m:'支出、費用',    e:'We need to reduce our monthly expenditures by 15%.'},
    {w:'profit margin',   m:'利潤率',        e:'Our profit margin improved by 3% this quarter.'},
    {w:'cash flow',       m:'現金流',        e:'Maintaining positive cash flow is critical for small businesses.'},
    {w:'audit',           m:'審計、查帳',    e:'The external audit found no significant issues this year.'},
    {w:'equity',          m:'股東權益',      e:'They raised capital through equity financing.'},
    {w:'liability',       m:'負債',          e:"The company's total liabilities exceed its current assets."},
    {w:'depreciation',    m:'折舊',          e:'Equipment depreciation must be recorded annually.'},
    {w:'balance sheet',   m:'資產負債表',    e:'The balance sheet shows total assets of $5 million.'},
    {w:'dividend',        m:'股息',          e:'Shareholders will receive a dividend of $2 per share.'},
    {w:'fiscal quarter',  m:'財政季度',      e:'Q3 results exceeded targets across all divisions.'},
    {w:'overhead',        m:'管銷費用',      e:'We are looking for ways to reduce overhead costs.'},
    {w:'accounts payable',m:'應付帳款',      e:'Accounts payable must be cleared within 60 days.'},
    {w:'accounts receivable',m:'應收帳款',   e:'Accounts receivable totals $2.3 million this quarter.'},
    {w:'amortization',    m:'分期攤還',      e:'Loan amortization is spread over 10 years.'},
    {w:'collateral',      m:'擔保品',        e:'The bank required property as collateral for the loan.'},
    {w:'net income',      m:'淨收入',        e:'Net income after taxes was $1.2 million last year.'},
    {w:'interest rate',   m:'利率',          e:'The loan carries a fixed interest rate of 3.5%.'},
    {w:'portfolio',       m:'投資組合',      e:'The investment portfolio performed well despite market volatility.'},
    {w:'write-off',       m:'沖銷、呆帳',   e:'The uncollectible debt was written off last fiscal year.'},
  ],
  patterns:[
    {p:'According to the + 文件',                e:'According to the quarterly report, revenue increased by 12%.',         t:'引用數據',   tw:'根據…'},
    {p:'The budget for + N + is + $',            e:'The budget for marketing activities this year is $500,000.',           t:'預算說明',   tw:'…的預算為…'},
    {p:'We expect + N/that + S+V',               e:'We expect profits to exceed targets this fiscal quarter.',             t:'財務預測',   tw:'我們預期…'},
    {p:'Compared to the same period last year',  e:'Compared to the same period last year, revenue grew by 18%.',         t:'同期比較',   tw:'與去年同期相比'},
    {p:'Operating costs have + V-ed by + %',     e:'Operating costs have decreased by 8% due to process improvements.',   t:'成本說明',   tw:'營運成本已…%'},
    {p:'The company has allocated + $ for + N',  e:'The company has allocated $2M for research and development.',         t:'撥款說明',   tw:'公司已撥款$…用於…'},
    {p:'Earnings per share + V-ed to + $',       e:'Earnings per share increased to $3.45 in the latest quarter.',        t:'每股盈餘',   tw:'每股盈餘…至$…'},
    {p:'The financial results reflect + N',      e:'The financial results reflect strong demand in emerging markets.',     t:'財報解讀',   tw:'財務結果反映…'},
  ],
  examTips:[
    'Part 7 常考：財報、預算報告、投資說明、貸款條件',
    'Part 5 常考：財務詞彙的詞性（noun/adj/verb）、固定搭配',
    'Part 3/4 常考：財務會議、預算審核、業績報告',
    '高頻題型：圖表整合題（季度業績圖/預算分配圖）',
    '關鍵字：budget / cash flow / audit / profit margin / balance sheet / write-off',
    'Ch16 重點：Part2 Q17/Q24, Part3 Q68-70, Part4 Q98-100, Part5 Q112/Q120, Part7 Q168-171',
    '注意：accounts payable（應付=我要付別人）≠ accounts receivable（應收=別人要付我）',
  ],
},

]; // end window.TOPICS_DATA
