// ════════════════════════════════════════
//  topics-data.js — 13 大主題完整資料
//  每主題：核心+進階單字(40+) / 句型 / 同義替換 / 常見錯誤 / 考試重點
// ════════════════════════════════════════
window.TOPICS_DATA = [

// ══════════════════════════════════
//  1. Travel 旅遊篇
// ══════════════════════════════════
{id:'travel',icon:'✈️',name:'Travel',nameTw:'旅遊篇',color:'#5b8fd4',desc:'機場、訂房、交通、行程安排',
vocab:[
  {w:'itinerary',m:'行程表',e:'Please send me the updated travel itinerary.',level:1},
  {w:'reservation',m:'預訂、訂位',e:'I would like to make a hotel reservation for three nights.',level:1},
  {w:'departure',m:'出發、起飛',e:'Our departure time has been moved to 8 AM.',level:1},
  {w:'accommodation',m:'住宿',e:'The conference includes accommodation for two nights.',level:1},
  {w:'layover',m:'中停、轉機',e:'We have a two-hour layover in Tokyo.',level:1},
  {w:'complimentary',m:'免費贈送的',e:'Breakfast is complimentary for all guests.',level:1},
  {w:'cancellation',m:'取消',e:'Late cancellation may result in a fee.',level:1},
  {w:'reimbursement',m:'費用報銷',e:'Submit your receipts for travel reimbursement.',level:1},
  {w:'boarding pass',m:'登機證',e:'Please have your boarding pass ready at the gate.',level:1},
  {w:'amenities',m:'設施、便利設備',e:'The hotel offers amenities such as a pool and gym.',level:1},
  {w:'round-trip',m:'來回票',e:'I would like to book a round-trip ticket to London.',level:1},
  {w:'check-in',m:'辦理入住/報到',e:'Online check-in is available 24 hours before departure.',level:1},
  {w:'customs',m:'海關',e:'You must declare items worth over $10,000 at customs.',level:1},
  {w:'delay',m:'延誤、延遲',e:'The flight was delayed by two hours due to fog.',level:1},
  {w:'confirmation',m:'確認、訂位確認',e:'Please keep your booking confirmation for reference.',level:1},
  {w:'transit visa',m:'過境簽證',e:'You may need a transit visa for the connecting flight.',level:2},
  {w:'excess baggage',m:'超重行李',e:'You may be charged for excess baggage.',level:2},
  {w:'per diem',m:'每日津貼',e:'Employees receive a per diem of $80 for business trips.',level:2},
  {w:'currency exchange',m:'外幣兌換',e:'Currency exchange is available at the airport.',level:2},
  {w:'porter',m:'行李員',e:'The porter will take your luggage to the room.',level:2},
  {w:'concierge',m:'飯店禮賓服務',e:'Ask the concierge for restaurant recommendations.',level:2},
  {w:'adjoining room',m:'相連客房',e:'We reserved adjoining rooms for the two families.',level:2},
  {w:'shuttle',m:'接駁車',e:'A complimentary shuttle runs between the hotel and airport.',level:2},
  {w:'voucher',m:'兌換券、抵用券',e:'Present this voucher at check-in for a free upgrade.',level:2},
  {w:'peak season',m:'旺季',e:'Hotel rates are higher during peak season.',level:2},
  {w:'off-peak',m:'淡季、離峰',e:'Off-peak travel is more affordable.',level:2},
  {w:'travel insurance',m:'旅遊保險',e:'Always purchase travel insurance before an international trip.',level:2},
  {w:'stopover',m:'短暫停留（中途）',e:'We planned a stopover in Dubai for sightseeing.',level:3},
  {w:'jet lag',m:'時差',e:'She was suffering from jet lag after the long flight.',level:3},
  {w:'bulk booking',m:'團體訂位',e:'Bulk bookings of 10+ rooms receive a 15% discount.',level:3},
],
patterns:[
  {p:'I would like to + V',e:'I would like to book a single room for two nights.',t:'禮貌請求',tw:'我想要…'},
  {p:'Is there a + N available?',e:'Is there a direct flight to Paris available on Friday?',t:'詢問是否有',tw:'請問有…嗎？'},
  {p:'Please be advised that + S+V',e:'Please be advised that check-in begins at 3 PM.',t:'公告提醒',tw:'請注意…'},
  {p:'due to + N',e:'The flight was delayed due to bad weather conditions.',t:'原因說明',tw:'由於…'},
  {p:'We regret to inform you that',e:'We regret to inform you that your flight has been canceled.',t:'遺憾通知',tw:'我們遺憾地通知您…'},
  {p:'subject to + N',e:'All reservations are subject to availability.',t:'視…而定',tw:'須視…而定'},
  {p:'prior to + N/V-ing',e:'Please check in prior to the departure time.',t:'在…之前',tw:'在…之前'},
  {p:'in the event of + N',e:'In the event of cancellation, a full refund will be issued.',t:'萬一…',tw:'萬一發生…'},
],
synonyms:[
  {word:'cancel',others:['call off','withdraw','void','nullify'],note:'cancel 最常用；void 常見於合約取消'},
  {word:'book / reserve',others:['make a reservation','secure a spot','schedule'],note:'book 和 reserve 幾乎可互換'},
  {word:'complimentary',others:['free of charge','no charge','at no cost','gratis'],note:'complimentary 是多益最常考的「免費」說法'},
  {word:'delay',others:['postpone','reschedule','push back','defer'],note:'delay 強調被動延誤；postpone 強調主動延後'},
  {word:'accommodation',others:['lodging','housing','quarters','dwelling'],note:'accommodation 是商務情境首選'},
],
commonErrors:[
  {wrong:'The flight was delayed for bad weather.',right:'The flight was delayed due to / because of bad weather.',explain:'"delay" 後面接原因用 due to / because of，不用 for'},
  {wrong:'I want to make a reservation on Friday.',right:'I want to make a reservation for Friday.',explain:'訂位「在某天」用 for，不用 on'},
  {wrong:'The hotel provides complimentary breakfast everyday.',right:'The hotel provides a complimentary breakfast every day.',explain:'every day 是兩個字，everyday 是形容詞（日常的）'},
  {wrong:'Please advice me on the check-in time.',right:'Please advise me on the check-in time.',explain:'advice 是名詞；advise 才是動詞'},
],
examTips:[
  'Part 3/4 常考：班機延誤、改期、轉機、飯店 check-in 問題、行程變更',
  'Part 7 常考：行程確認 email、飯店取消政策、旅遊廣告、機票訂購說明',
  'Part 2 常考：詢問航班/訂房狀態、確認時間地點',
  '高頻陷阱：complimentary（免費的）看起來像 compliment（稱讚），意思完全不同',
  '同義替換：book = reserve = make a reservation；delay = be pushed back',
  '關鍵字：itinerary / round-trip / one-way / complimentary / amenities / per diem',
],
},

// ══════════════════════════════════
//  2. Dining Out 外出用餐篇
// ══════════════════════════════════
{id:'dining',icon:'🍽️',name:'Dining Out',nameTw:'外出用餐篇',color:'#e8a44a',desc:'餐廳訂位、點餐、外燴、餐飲服務',
vocab:[
  {w:'reservation',m:'訂位',e:'I have a reservation under the name Smith.',level:1},
  {w:'appetizer',m:'開胃菜',e:'Would you like to start with an appetizer?',level:1},
  {w:'cuisine',m:'料理、烹飪風格',e:'The restaurant is known for its French cuisine.',level:1},
  {w:'catering',m:'外燴服務',e:'We hired a catering company for the annual event.',level:1},
  {w:'dietary',m:'飲食的',e:'Please let us know of any dietary restrictions.',level:1},
  {w:'gratuity',m:'小費、服務費',e:'A 15% gratuity is included in the bill.',level:1},
  {w:'specials',m:'今日特餐',e:"Today's specials include grilled salmon.",level:1},
  {w:'banquet',m:'宴席、宴會',e:'The company dinner will be a banquet-style event.',level:1},
  {w:'buffet',m:'自助式餐廳',e:'Lunch will be served buffet style.',level:1},
  {w:'takeout',m:'外帶',e:'Would you prefer dine-in or takeout?',level:1},
  {w:'entrée',m:'主菜',e:'The entrée comes with a choice of soup or salad.',level:1},
  {w:'beverage',m:'飲料',e:'All beverages are included in the prix fixe menu.',level:1},
  {w:'allergy',m:'過敏',e:'Please inform us of any food allergies in advance.',level:1},
  {w:'complimentary',m:'免費贈送的',e:'Complimentary drinks are served upon arrival.',level:1},
  {w:'host',m:'接待人員',e:'The host will escort you to your table.',level:1},
  {w:'vegan',m:'純素的',e:'We offer a vegan menu for plant-based diners.',level:2},
  {w:'prix fixe',m:'固定價格套餐',e:'The prix fixe dinner is $45 per person.',level:2},
  {w:'seating capacity',m:'座位容量',e:'The banquet hall has a seating capacity of 200.',level:2},
  {w:'private dining',m:'包廂用餐',e:'A private dining room is available for groups of 10+.',level:2},
  {w:'corkage fee',m:'開瓶費',e:'There is a $15 corkage fee for outside wine.',level:2},
  {w:'mise en place',m:'備料就緒（廚房術語）',e:'Chefs use mise en place to prepare ingredients ahead of time.',level:2},
  {w:'sommelier',m:'侍酒師',e:'The sommelier recommended a local red wine.',level:2},
  {w:'à la carte',m:'單點制',e:'The menu is available à la carte or as a set meal.',level:2},
  {w:'tasting menu',m:'品嚐套餐',e:'The tasting menu features eight seasonal courses.',level:3},
  {w:'no-show',m:'訂位未出席',e:'No-shows will be charged a cancellation fee.',level:3},
],
patterns:[
  {p:"I'd like to reserve a table for + 人數",e:"I'd like to reserve a table for six at 7 PM tonight.",t:'訂位',tw:'我想訂…人的位子'},
  {p:'Do you have anything + adj?',e:'Do you have anything vegetarian on the menu?',t:'詢問菜單',tw:'有…的選項嗎？'},
  {p:'Could you accommodate + N?',e:'Could you accommodate a special dietary request?',t:'特殊要求',tw:'能否配合…？'},
  {p:'The set menu includes + N',e:'The set menu includes three courses and a beverage.',t:'套餐說明',tw:'套餐包含…'},
  {p:'A minimum charge of + $ applies',e:'A minimum charge of $20 per person applies on weekends.',t:'最低消費',tw:'最低消費為…'},
  {p:'Please inform us in advance if + S+V',e:'Please inform us in advance if you have any allergies.',t:'提前告知',tw:'如有…請提前告知'},
  {p:'We apologize for the wait',e:'We apologize for the wait and appreciate your patience.',t:'等候致歉',tw:'為等候時間道歉'},
],
synonyms:[
  {word:'reservation',others:['booking','appointment','table booking'],note:'reservation 和 booking 幾乎可互換'},
  {word:'gratuity',others:['tip','service charge','surcharge'],note:'gratuity 是正式說法；tip 較口語'},
  {word:'dietary restriction',others:['food intolerance','food allergy','special dietary need'],note:'三者語意相近但程度不同'},
  {word:'complimentary',others:['on the house','free of charge','courtesy'],note:'"on the house" 是餐飲業特有說法'},
],
commonErrors:[
  {wrong:'Do you have a table for we?',right:'Do you have a table for us?',explain:'介系詞後面用受格 us，不用主格 we'},
  {wrong:'The gratuity is not included.',right:'Gratuity is not included. / The gratuity has not been included.',explain:'注意 include 的時態和冠詞用法'},
  {wrong:'I am allergic with peanuts.',right:'I am allergic to peanuts.',explain:'allergic 固定搭配 to，不用 with'},
  {wrong:'We would like to make a book.',right:'We would like to make a reservation / booking.',explain:'book 作名詞是「書」；訂位要用 reservation 或 booking'},
],
examTips:[
  'Part 3 常考：餐廳預訂問題、服務投訴、菜單詢問、外燴協商',
  'Part 4 常考：餐廳廣告、外燴服務說明、活動用餐公告',
  'Part 7 常考：餐廳評論、外燴合約、菜單說明、訂位確認信',
  '高頻陷阱：gratuity（服務費）通常已包含在帳單內，選項可能說「不包含」是陷阱',
  '同義替換：book = reserve；gratuity = tip = service charge',
  '關鍵字：reservation / dietary restriction / complimentary / gratuity / catering',
],
},

// ══════════════════════════════════
//  3. Entertainment 娛樂篇
// ══════════════════════════════════
{id:'entertainment',icon:'🎭',name:'Entertainment',nameTw:'娛樂篇',color:'#9b7fe8',desc:'展覽、表演、活動、票務',
vocab:[
  {w:'venue',m:'場地、會場',e:'The concert venue holds up to 5,000 people.',level:1},
  {w:'admission',m:'入場費',e:'Admission is free for children under 12.',level:1},
  {w:'intermission',m:'中場休息',e:'There will be a 15-minute intermission after Act 2.',level:1},
  {w:'exhibit',m:'展覽（品）',e:'The art exhibit will run through the end of the month.',level:1},
  {w:'sold out',m:'售罄',e:'The Saturday performance is already sold out.',level:1},
  {w:'box office',m:'售票處',e:'Tickets are available at the box office from 10 AM.',level:1},
  {w:'lineup',m:'陣容、節目表',e:"This year's festival lineup features 30 performers.",level:1},
  {w:'premiere',m:'首映、首演',e:'The premiere is scheduled for next Friday evening.',level:1},
  {w:'ticket stub',m:'票根',e:'Please keep your ticket stub for re-entry.',level:1},
  {w:'featured',m:'特別呈現的',e:'The festival featured works by local directors.',level:1},
  {w:'gallery',m:'藝廊、展覽館',e:'The gallery is open Tuesday through Sunday.',level:1},
  {w:'matinee',m:'日場演出',e:'Matinee tickets are discounted by 20%.',level:1},
  {w:'merchandise',m:'周邊商品',e:'Official merchandise is available at the gift shop.',level:1},
  {w:'program',m:'節目單',e:'A program is included with each ticket purchase.',level:1},
  {w:'opening night',m:'首演之夜',e:'Opening night tickets are nearly sold out.',level:1},
  {w:'curator',m:'策展人',e:'The curator will give a guided tour at 2 PM.',level:2},
  {w:'backstage',m:'後台',e:'VIP ticket holders can access the backstage area.',level:2},
  {w:'standing ovation',m:'起立鼓掌',e:'The performance received a standing ovation.',level:2},
  {w:'ensemble',m:'劇團、合奏團',e:'The ensemble has been performing for over 20 years.',level:2},
  {w:'rehearsal',m:'排練、彩排',e:'The dress rehearsal is scheduled for Thursday.',level:2},
  {w:'subsidized',m:'獲補助的',e:'The theater is subsidized by government arts funding.',level:2},
  {w:'patron',m:'贊助人、常客',e:'Museum patrons enjoy free admission year-round.',level:2},
  {w:'usher',m:'引座員',e:'An usher will show you to your seat.',level:2},
  {w:'concession stand',m:'小賣部',e:'Refreshments are available at the concession stand.',level:3},
  {w:'marquee',m:'大帳篷；戲院招牌',e:'The show name is displayed on the theater marquee.',level:3},
],
patterns:[
  {p:'Tickets are available + 地點/方式',e:'Tickets are available online or at the door on the night.',t:'售票資訊',tw:'票券可在…購得'},
  {p:'The event will be held + 時地',e:'The event will be held at the Grand Theater on March 15th.',t:'活動舉行',tw:'活動將於…舉行'},
  {p:'For more information, + V',e:'For more information, please visit our official website.',t:'更多資訊',tw:'更多資訊請…'},
  {p:'Seating is on a first-come basis',e:'Seating for the free event is on a first-come, first-served basis.',t:'先到先得',tw:'座位採先到先得'},
  {p:'Doors open at + 時間',e:'Doors open at 7:00 PM, one hour before the show.',t:'開門時間',tw:'大門於…開放'},
  {p:'In the event of cancellation, + S+V',e:'In the event of cancellation, ticket holders will be refunded.',t:'取消政策',tw:'若活動取消…'},
],
synonyms:[
  {word:'admission',others:['entry fee','entrance fee','cover charge','ticket price'],note:'admission 最常見；cover charge 多用於酒吧'},
  {word:'sold out',others:['fully booked','at capacity','no longer available','unavailable'],note:'sold out 是考試最常用的同義替換'},
  {word:'venue',others:['location','site','facility','arena','hall'],note:'venue 是正式活動場地首選'},
  {word:'exhibit',others:['display','exhibition','show','showcase'],note:'exhibit（單件展品）；exhibition（整個展覽）'},
],
commonErrors:[
  {wrong:'The show is fully booked out.',right:'The show is fully booked. / The show is sold out.',explain:'fully booked 和 sold out 不需要加 out'},
  {wrong:'Admission fee is free for students.',right:'Admission is free for students.',explain:'admission 本身已包含費用概念，不需加 fee'},
  {wrong:'The concert will held at City Hall.',right:'The concert will be held at City Hall.',explain:'被動語態：will be held，不能省略 be'},
],
examTips:[
  'Part 4 常考：廣播節目介紹、表演廣告、活動公告',
  'Part 7 常考：活動公告、展覽說明、票務規則、評論',
  'Part 2 常考：詢問票務、演出時間、場地位置',
  '高頻題型：Look at the graphic（時間表/節目單）整合題',
  '同義替換：sold out = fully booked = at capacity = no tickets available',
  '關鍵字：admission / venue / sold out / intermission / box office / matinee',
],
},

// ══════════════════════════════════
//  4. Housing 房屋篇
// ══════════════════════════════════
{id:'housing',icon:'🏠',name:'Housing',nameTw:'房屋篇',color:'#4caf82',desc:'租屋、買賣、維修、物業管理',
vocab:[
  {w:'lease',m:'租約、租賃',e:'The lease agreement is for one year with an option to renew.',level:1},
  {w:'landlord',m:'房東',e:'The landlord agreed to repaint the apartment before move-in.',level:1},
  {w:'deposit',m:'押金、定金',e:'A security deposit equal to one month rent is required.',level:1},
  {w:'utilities',m:'水電費',e:'Utilities are not included in the monthly rent.',level:1},
  {w:'renovation',m:'整修、翻新',e:'The building is undergoing major renovation this summer.',level:1},
  {w:'tenant',m:'承租人、房客',e:'The tenant is responsible for minor repairs under $100.',level:1},
  {w:'vacancy',m:'空缺、空屋',e:'There are currently two vacancies in the building.',level:1},
  {w:'maintenance',m:'維護、保養',e:'Report any maintenance issues to the building manager.',level:1},
  {w:'mortgage',m:'抵押貸款',e:'They applied for a 30-year mortgage at a fixed rate.',level:1},
  {w:'property',m:'房產、物業',e:'The company owns several commercial properties downtown.',level:1},
  {w:'real estate',m:'不動產',e:'She works as a real estate agent in the downtown area.',level:1},
  {w:'floor plan',m:'平面圖',e:'Could you send me the floor plan for the unit?',level:1},
  {w:'association fee',m:'管理費',e:'The monthly association fee covers building maintenance.',level:1},
  {w:'sublease',m:'轉租',e:'Subleasing is not permitted without written approval.',level:2},
  {w:'appraisal',m:'估價',e:'An independent appraisal determined the property value.',level:2},
  {w:'homeowner',m:'房屋所有人',e:'Homeowners are responsible for their own property taxes.',level:2},
  {w:'eviction',m:'驅逐、驅離',e:'The landlord filed for eviction due to unpaid rent.',level:2},
  {w:'condominium',m:'公寓大廈',e:'She purchased a condominium on the 15th floor.',level:2},
  {w:'zoning',m:'分區規劃',e:'The area is zoned for residential use only.',level:2},
  {w:'property tax',m:'房產稅',e:'Property taxes are paid annually to the local government.',level:2},
  {w:'inspection',m:'驗屋、檢查',e:'A home inspection is required before closing the deal.',level:2},
  {w:'down payment',m:'頭期款',e:'A 20% down payment is required for the mortgage.',level:2},
  {w:'closing costs',m:'過戶費用',e:'Closing costs typically range from 2% to 5% of the loan.',level:3},
  {w:'lien',m:'留置權',e:'The contractor placed a lien on the property.',level:3},
  {w:'amortization',m:'攤還（貸款）',e:'The amortization schedule shows monthly payments.',level:3},
],
patterns:[
  {p:'The rent is + $ per month',e:'The rent is $1,500 per month, utilities included.',t:'租金說明',tw:'租金為…'},
  {p:'Subject to + N',e:'All renovations are subject to management approval.',t:'需經審核',tw:'需視…而定'},
  {p:'Effective + date',e:'The new lease terms are effective January 1st.',t:'生效日期',tw:'自…起生效'},
  {p:'The tenant is responsible for + N',e:'The tenant is responsible for maintaining the garden.',t:'責任歸屬',tw:'承租人須負責…'},
  {p:'Prior written notice of + 天數 days',e:'Prior written notice of 30 days is required to terminate.',t:'提前通知',tw:'需提前…天書面通知'},
  {p:'Failure to + V will result in + N',e:'Failure to pay rent on time will result in a late fee.',t:'違約後果',tw:'未能…將導致…'},
],
synonyms:[
  {word:'landlord',others:['property owner','lessor','building owner'],note:'landlord 最常用；lessor 是法律術語'},
  {word:'tenant',others:['renter','lessee','occupant','resident'],note:'tenant 最常考；lessee 是法律術語'},
  {word:'lease',others:['rental agreement','tenancy agreement','contract'],note:'lease 強調租約文件'},
  {word:'deposit',others:['security deposit','down payment','retainer'],note:'security deposit（押金）；down payment（頭期款）不同'},
  {word:'maintenance',others:['upkeep','repairs','servicing','preservation'],note:'maintenance 包含定期保養；repair 強調修繕'},
],
commonErrors:[
  {wrong:'The tenant must pay the rent on the first of each month.',right:'The tenant must pay rent on the first of each month.',explain:'rent 作「租金」時通常不加冠詞'},
  {wrong:'The deposit will refund after moving out.',right:'The deposit will be refunded after moving out.',explain:'refund 作動詞時，押金「被退還」要用被動語態'},
  {wrong:'The apartment is on a good condition.',right:'The apartment is in good condition.',explain:'「狀況」用 in condition，不用 on'},
],
examTips:[
  'Part 3 常考：房客與房東的溝通、維修請求、合約問題',
  'Part 7 常考：租約條款、維修通知、公寓廣告、物業管理公告',
  'Part 4 常考：大樓停車場、設施維修、公告',
  '高頻陷阱：deposit（押金）≠ monthly rent，不要搞混金額',
  '同義替換：landlord = property owner；tenant = renter = lessee',
  '關鍵字：lease / deposit / utilities / tenant / maintenance / sublease',
],
},

// ══════════════════════════════════
//  5. Purchasing 採購篇
// ══════════════════════════════════
{id:'purchasing',icon:'🛒',name:'Purchasing',nameTw:'採購篇',color:'#e05c5c',desc:'訂購、議價、供應商、付款條件',
vocab:[
  {w:'invoice',m:'發票、帳單',e:'Please send the invoice to our accounting department.',level:1},
  {w:'purchase order',m:'採購訂單',e:'A purchase order must be approved before placing the order.',level:1},
  {w:'vendor',m:'供應商',e:'We are comparing quotes from three different vendors.',level:1},
  {w:'quote',m:'報價',e:'Could you send us a quote for 200 units?',level:1},
  {w:'warranty',m:'保固',e:'The product comes with a one-year warranty.',level:1},
  {w:'defective',m:'有缺陷的',e:'We received a shipment of defective parts last week.',level:1},
  {w:'backorder',m:'延期交貨訂單',e:'The item is on backorder and will ship in two weeks.',level:1},
  {w:'bulk discount',m:'批量折扣',e:'A bulk discount is available for orders over 500 units.',level:1},
  {w:'procurement',m:'採購（正式）',e:'Our procurement team handles all supplier contracts.',level:1},
  {w:'net 30',m:'30天付款條件',e:'Payment terms are net 30 from the invoice date.',level:1},
  {w:'inventory',m:'庫存',e:'Current inventory levels are sufficient for two months.',level:1},
  {w:'freight',m:'貨運費',e:'Freight costs are included in the quoted price.',level:1},
  {w:'return policy',m:'退貨政策',e:'Our return policy allows returns within 30 days.',level:1},
  {w:'lead time',m:'前置時間',e:'The lead time for custom orders is six weeks.',level:2},
  {w:'RFQ',m:'詢價單',e:'We sent out an RFQ to five potential suppliers.',level:2},
  {w:'wholesale',m:'批發',e:'Wholesale prices are available for orders over 1,000 units.',level:2},
  {w:'consignment',m:'寄售',e:'Goods are delivered on consignment and paid after sale.',level:2},
  {w:'compliance',m:'遵守規定',e:'All vendors must demonstrate regulatory compliance.',level:2},
  {w:'COD',m:'貨到付款',e:'Small orders may be placed on a COD basis.',level:2},
  {w:'price negotiation',m:'議價',e:'Price negotiation is expected for large volume orders.',level:2},
  {w:'restocking fee',m:'補貨費',e:'A 15% restocking fee applies to all returned items.',level:2},
  {w:'bid',m:'投標',e:'Three companies submitted bids for the contract.',level:2},
  {w:'tender',m:'招標',e:'The project was put out to tender last month.',level:3},
  {w:'force majeure',m:'不可抗力',e:'The delay was classified as force majeure.',level:3},
],
patterns:[
  {p:'We would like to place an order for + N',e:'We would like to place an order for 300 units of item #A201.',t:'下訂單',tw:'我們想訂購…'},
  {p:'Could you provide a quote for + N?',e:'Could you provide a quote for bulk printing of 5,000 copies?',t:'詢價',tw:'能否提供…的報價？'},
  {p:'The shipment is scheduled for + date',e:'The shipment is scheduled for delivery on Friday, March 10.',t:'出貨說明',tw:'貨物預計於…出貨'},
  {p:'Please confirm receipt of + N',e:'Please confirm receipt of this purchase order by end of day.',t:'確認收到',tw:'請確認已收到…'},
  {p:'Payment is due within + N days of + N',e:'Payment is due within 30 days of invoice receipt.',t:'付款期限',tw:'付款期限為…天內'},
  {p:'A restocking fee of + % applies',e:'A restocking fee of 15% applies to all returned merchandise.',t:'補貨費',tw:'退貨須支付…%的補貨費'},
],
synonyms:[
  {word:'vendor',others:['supplier','provider','seller','distributor'],note:'vendor 和 supplier 幾乎可互換'},
  {word:'invoice',others:['bill','statement','receipt','charge'],note:'invoice（正式帳單）；receipt（收據，付款後）'},
  {word:'defective',others:['faulty','damaged','flawed','substandard'],note:'defective 最常考；faulty 也常見'},
  {word:'quote',others:['estimate','bid','proposal','offer'],note:'quote/estimate 是非正式報價；bid 是競標報價'},
  {word:'purchase',others:['buy','acquire','obtain','procure'],note:'procure 是最正式的採購說法'},
],
commonErrors:[
  {wrong:'We want to order 500 units of products.',right:'We want to order 500 units of the product.',explain:'特定產品用定冠詞 the product，或直接說 500 units'},
  {wrong:'The payment should do within 30 days.',right:'The payment should be made within 30 days.',explain:'付款 "做出" 要用 make a payment / payment should be made'},
  {wrong:'Please send us a price list for our reference.',right:'Please send us a price list for our reference.',explain:'這句沒錯，但注意 for reference 不需要加 our（可省略）'},
],
examTips:[
  'Part 7 常考：採購 email、發票、訂單確認、供應商合約',
  'Part 3 常考：採購部門對話、供應商協商、訂單問題',
  'Part 5 常考：採購相關詞彙的詞性和介系詞搭配',
  '高頻題型：雙篇文章（採購訂單 + 回覆 email）',
  '同義替換：vendor = supplier；defective = faulty；quote = estimate',
  '關鍵字：invoice / purchase order / vendor / backorder / net 30 / lead time',
],
},

// ══════════════════════════════════
//  6. Personnel 人事篇
// ══════════════════════════════════
{id:'personnel',icon:'👥',name:'Personnel',nameTw:'人事篇',color:'#5b8fd4',desc:'招聘、面試、升遷、績效評估',
vocab:[
  {w:'recruitment',m:'招聘',e:'The recruitment process takes about four weeks.',level:1},
  {w:'applicant',m:'求職者、申請人',e:'We received over 200 applicants for the position.',level:1},
  {w:'resume/CV',m:'履歷',e:'Please submit your resume and a cover letter.',level:1},
  {w:'probation',m:'試用期',e:'New employees undergo a 90-day probation period.',level:1},
  {w:'performance review',m:'績效評估',e:'Annual performance reviews are held in December.',level:1},
  {w:'promotion',m:'晉升',e:'She received a promotion to Senior Manager last month.',level:1},
  {w:'payroll',m:'薪資發放',e:'The payroll department handles all salary processing.',level:1},
  {w:'incentive',m:'獎勵、激勵',e:'Sales staff receive a quarterly incentive bonus.',level:1},
  {w:'onboarding',m:'新人培訓流程',e:'Our onboarding program lasts two weeks.',level:1},
  {w:'benefits',m:'福利',e:'Benefits include health insurance and a retirement plan.',level:1},
  {w:'resignation',m:'辭職',e:'Her resignation took effect at the end of the month.',level:1},
  {w:'job description',m:'職位說明',e:'Please review the job description before applying.',level:1},
  {w:'compensation',m:'薪酬、補償',e:'Compensation includes salary, bonus, and benefits.',level:1},
  {w:'reference',m:'推薦人、推薦信',e:'Please provide two professional references.',level:2},
  {w:'termination',m:'終止（合約/職務）',e:'Termination of employment requires two weeks notice.',level:2},
  {w:'severance',m:'資遣費',e:'Laid-off employees will receive severance packages.',level:2},
  {w:'intern',m:'實習生',e:'We hire ten interns every summer semester.',level:2},
  {w:'headhunter',m:'獵人頭',e:'The position was filled through a headhunter firm.',level:2},
  {w:'overtime',m:'加班',e:'Overtime pay is 1.5 times the regular hourly rate.',level:2},
  {w:'workforce',m:'勞動力、員工總數',e:'The company expanded its workforce by 200 employees.',level:2},
  {w:'non-disclosure agreement',m:'保密協議',e:'All new hires must sign a non-disclosure agreement.',level:2},
  {w:'exempt',m:'免除的（法規）',e:'Salaried managers are often exempt from overtime rules.',level:2},
  {w:'attrition',m:'自然減員',e:'Staff attrition has increased due to low morale.',level:3},
  {w:'succession planning',m:'接班人計畫',e:'Succession planning ensures business continuity.',level:3},
],
patterns:[
  {p:'We are looking for candidates with + N',e:'We are looking for candidates with five years of relevant experience.',t:'徵才條件',tw:'我們尋找具備…的人才'},
  {p:'The position requires + N/V-ing',e:'The position requires fluency in English and Mandarin.',t:'職位要求',tw:'此職位需要…'},
  {p:'We are pleased to offer you + N',e:'We are pleased to offer you the position of Marketing Manager.',t:'錄取通知',tw:'我們很高興提供您…職位'},
  {p:'Salary is commensurate with + N',e:'Salary is commensurate with experience and qualifications.',t:'薪資說明',tw:'薪資依…而定'},
  {p:'Qualified candidates should + V',e:'Qualified candidates should submit applications by March 31st.',t:'應徵說明',tw:'符合資格的應徵者應…'},
  {p:'Effective + date, + S+V',e:'Effective January 1st, the new HR policy will be in place.',t:'生效公告',tw:'自…起，…'},
  {p:'Following a review of + N, we + V',e:'Following a review of your application, we would like to interview you.',t:'邀請面試',tw:'審核…後，我們…'},
],
synonyms:[
  {word:'applicant',others:['candidate','job seeker','interviewee','prospect'],note:'applicant（申請者）；candidate（候選人）在錄取後使用'},
  {word:'hire',others:['employ','recruit','take on','bring on board'],note:'hire 最口語；employ 較正式'},
  {word:'fire / dismiss',others:['terminate','lay off','let go','release'],note:'lay off（因業務緊縮裁員）≠ fire（因表現解雇）'},
  {word:'salary',others:['compensation','remuneration','pay','wages'],note:'salary（固定月薪）；wages（時薪）'},
],
commonErrors:[
  {wrong:'She was promoted as Manager.',right:'She was promoted to Manager.',explain:'晉升「到某個職位」用 promoted to，不用 as'},
  {wrong:'Please send your resume to apply the position.',right:'Please send your resume to apply for the position.',explain:'apply 後面接 for，不直接接受詞'},
  {wrong:'He resigned from his job yesterday.',right:'He resigned from his position / job yesterday.',explain:'resign from 是正確搭配，但 resigned his position 也正確'},
  {wrong:'The salary is negotiable depends on experience.',right:'The salary is negotiable depending on experience.',explain:'不能用 depends，要用分詞 depending on'},
],
examTips:[
  'Part 7 常考：職缺廣告、錄取通知、績效評估表、離職信',
  'Part 3 常考：面試情景、升遷/調職通知、績效討論',
  'Part 4 常考：公司公告（人事異動）、歡迎新員工',
  '高頻題型：Who most likely is the speaker? = 判斷說話者身份',
  '同義替換：hire = employ = recruit；fire = dismiss = terminate = let go',
  '關鍵字：recruitment / probation / performance review / onboarding / compensation',
],
},

// ══════════════════════════════════
//  7. Offices 辦公室篇
// ══════════════════════════════════
{id:'offices',icon:'🏢',name:'Offices',nameTw:'辦公室篇',color:'#e8b86d',desc:'辦公設備、會議、行政、文件處理',
vocab:[
  {w:'agenda',m:'議程',e:'Please review the agenda before the meeting.',level:1},
  {w:'minutes',m:'會議記錄',e:'Sarah will take the minutes during the meeting.',level:1},
  {w:'memo',m:'備忘錄',e:'A memo was sent to all staff about the policy change.',level:1},
  {w:'deadline',m:'截止日期',e:'The report deadline is this Friday at 5 PM.',level:1},
  {w:'cc',m:'副本（電郵）',e:'Please cc the finance department on this email.',level:1},
  {w:'conference call',m:'電話會議',e:'We will have a conference call with the Tokyo office.',level:1},
  {w:'workload',m:'工作量',e:'The new hire will help reduce our workload significantly.',level:1},
  {w:'delegate',m:'委派工作',e:'The manager delegated the task to her assistant.',level:1},
  {w:'copier',m:'影印機',e:'The copier on the third floor is currently out of order.',level:1},
  {w:'receptionist',m:'接待人員',e:'The receptionist will direct visitors to the meeting room.',level:1},
  {w:'out of office',m:'外出/不在辦公室',e:'I will be out of office from March 10-15.',level:1},
  {w:'filing',m:'歸檔',e:'Electronic filing has replaced most paper-based systems.',level:1},
  {w:'workflow',m:'工作流程',e:'We are looking for ways to streamline the workflow.',level:1},
  {w:'telecommute',m:'遠距辦公',e:'Employees may telecommute up to two days per week.',level:2},
  {w:'stationery',m:'文具',e:'Office stationery can be ordered through the supply portal.',level:2},
  {w:'projector',m:'投影機',e:'Please set up the projector before the presentation.',level:2},
  {w:'archive',m:'封存、資料庫',e:'Please archive completed project files in the shared drive.',level:2},
  {w:'initiative',m:'主動、新計畫',e:'The office recycling initiative was very successful.',level:2},
  {w:'cubicle',m:'隔間辦公桌',e:'Each employee has their own cubicle on the third floor.',level:2},
  {w:'circulation',m:'流傳、發行',e:'Please limit internal email circulation to relevant staff.',level:2},
  {w:'hot-desking',m:'共用辦公桌',e:'Hot-desking allows employees to use any available desk.',level:2},
  {w:'protocol',m:'規範、協議',e:'Please follow the office protocol for visitor registration.',level:2},
  {w:'stipulate',m:'規定、明定',e:'The policy stipulates that all overtime must be approved.',level:3},
  {w:'overhead projector',m:'高射投影機',e:'The overhead projector was replaced by a digital display.',level:3},
],
patterns:[
  {p:'The meeting is scheduled for + 時間',e:'The meeting is scheduled for 2 PM in Conference Room B.',t:'會議安排',tw:'會議安排於…'},
  {p:'Please ensure that + S+V',e:'Please ensure that all reports are submitted by end of day Friday.',t:'確認事項',tw:'請確保…'},
  {p:'I am writing to + V',e:'I am writing to inform you of a schedule change for next week.',t:'電郵開頭',tw:'我寫信是為了…'},
  {p:'As a reminder, + S+V',e:'As a reminder, the office will be closed on Monday.',t:'提醒事項',tw:'提醒您…'},
  {p:'Going forward, + S+V',e:'Going forward, all requests must be submitted through the new system.',t:'今後方針',tw:'今後…'},
  {p:'For your reference, + S+V',e:'For your reference, the updated policy is attached.',t:'供參考',tw:'供您參考…'},
  {p:'Kindly + V by + 時間',e:'Kindly return the signed form by this Friday.',t:'禮貌請求',tw:'煩請於…前…'},
  {p:'Please be aware that + S+V',e:'Please be aware that the server will be down for maintenance tonight.',t:'注意事項',tw:'請注意…'},
],
synonyms:[
  {word:'memo',others:['memorandum','internal notice','circular','bulletin'],note:'memo 是 memorandum 的縮寫，多益兩種都考'},
  {word:'agenda',others:['schedule','program','plan','itinerary'],note:'agenda 特指會議議程'},
  {word:'deadline',others:['due date','cutoff date','submission date','target date'],note:'deadline 最常考；cutoff 強調截止後不接受'},
  {word:'meeting',others:['conference','session','gathering','assembly'],note:'conference 通常較大型；session 強調一段時間'},
],
commonErrors:[
  {wrong:'The meeting will hold in Room 3.',right:'The meeting will be held in Room 3.',explain:'被動語態：will be held，hold 不能直接用主動'},
  {wrong:'Please advice your team about the change.',right:'Please advise your team about the change.',explain:'advice 是名詞；advise 是動詞'},
  {wrong:'I am writing to you regarding with the report.',right:'I am writing to you regarding the report.',explain:'regarding 本身已是介系詞，後面不加 with'},
  {wrong:'Let\'s discuss about the budget.',right:"Let's discuss the budget.",explain:'discuss 是及物動詞，不需要加 about'},
],
examTips:[
  'Part 3 常考：會議安排、工作分配、設備故障、電話留言',
  'Part 6/7 常考：備忘錄格式（To/From/Date/Re）、內部公告、email',
  'Part 2 常考：確認會議時間地點、詢問任務分配',
  '高頻文體：memo 格式是多益必考，記住 To / From / Date / Subject 四要素',
  '同義替換：memo = memorandum；deadline = due date = cutoff',
  '關鍵字：agenda / minutes / deadline / cc / delegate / telecommute',
],
},

// ══════════════════════════════════
//  8. Health 健康篇
// ══════════════════════════════════
{id:'health',icon:'🏥',name:'Health',nameTw:'健康篇',color:'#4caf82',desc:'醫療保險、預約、職場健康',
vocab:[
  {w:'prescription',m:'處方箋',e:'You need a prescription for this medication.',level:1},
  {w:'insurance',m:'保險',e:'Our company provides full health insurance coverage.',level:1},
  {w:'coverage',m:'保險範圍、涵蓋',e:'Does your insurance coverage include dental?',level:1},
  {w:'deductible',m:'自付額（保險）',e:'The annual deductible is $500 per person.',level:1},
  {w:'specialist',m:'專科醫師',e:'Your doctor referred you to a cardiologist specialist.',level:1},
  {w:'wellness',m:'健康促進',e:'The company offers a wellness program for all employees.',level:1},
  {w:'pharmacy',m:'藥局',e:'The prescription can be filled at any participating pharmacy.',level:1},
  {w:'checkup',m:'健康檢查',e:'Annual checkups are covered by the insurance plan.',level:1},
  {w:'ergonomic',m:'符合人體工學的',e:'We provide ergonomic chairs and desks for all staff.',level:1},
  {w:'symptoms',m:'症狀',e:'Please describe your symptoms to the nurse first.',level:1},
  {w:'sick leave',m:'病假',e:'Full-time employees receive 10 days of paid sick leave.',level:1},
  {w:'claim',m:'保險申請',e:'Submit your medical receipts to file an insurance claim.',level:1},
  {w:'copayment',m:'部分自付額',e:'There is a $20 copayment for each doctor visit.',level:2},
  {w:'premium',m:'保險費',e:'The monthly premium is deducted directly from payroll.',level:2},
  {w:'referral',m:'轉介、轉診',e:'You need a referral to see a specialist.',level:2},
  {w:'out-of-network',m:'非網絡內（保險）',e:'Out-of-network visits are only partially covered.',level:2},
  {w:'EAP',m:'員工協助計畫',e:'Our EAP offers free counseling sessions for employees.',level:2},
  {w:'generic',m:'學名藥',e:'Ask your pharmacist about a generic alternative to reduce cost.',level:2},
  {w:'pre-existing',m:'既往症',e:'Pre-existing conditions may affect your coverage.',level:2},
  {w:'occupational hazard',m:'職業危害',e:'Occupational hazards must be reported to HR immediately.',level:2},
  {w:'open enrollment',m:'保險選擇期',e:'Open enrollment for next year\'s benefits begins in October.',level:2},
  {w:'formulary',m:'藥品給付表',e:'Check the formulary to see if your medication is covered.',level:3},
  {w:'FSA',m:'彈性支出帳戶',e:'Use your FSA funds before the end of the year.',level:3},
],
patterns:[
  {p:"I'd like to make an appointment with + 醫師",e:"I'd like to make an appointment with Dr. Lee for Monday afternoon.",t:'預約看診',tw:'我想預約…醫師'},
  {p:'Your insurance covers + N',e:'Your insurance covers up to $200 annually for eyewear.',t:'保險說明',tw:'你的保險涵蓋…'},
  {p:'Coverage is provided for + N',e:'Coverage is provided for preventive care and annual checkups.',t:'涵蓋範圍',tw:'保險涵蓋…'},
  {p:'A copayment of + $ is required for + N',e:'A copayment of $30 is required for specialist visits.',t:'自付說明',tw:'…需支付$…自付額'},
  {p:'Employees are eligible for + N after + N',e:'Employees are eligible for dental benefits after 90 days.',t:'福利資格',tw:'員工在…後有資格享有…'},
  {p:'In case of emergency, proceed to + 地點',e:'In case of emergency, proceed to the nearest urgent care center.',t:'緊急處置',tw:'緊急情況請前往…'},
  {p:'Please contact + 部門 + regarding + N',e:'Please contact HR regarding your health insurance benefits.',t:'聯絡指引',tw:'請聯絡…關於…'},
],
synonyms:[
  {word:'coverage',others:['benefits','plan','policy','protection'],note:'coverage 最常考；benefits 強調福利內容'},
  {word:'prescription',others:['medication order','Rx','doctor\'s order'],note:'Rx 是處方箋的縮寫，偶爾出現'},
  {word:'checkup',others:['physical examination','medical exam','health screening'],note:'annual checkup = annual physical = yearly exam'},
  {word:'deductible',others:['out-of-pocket expense','self-pay amount'],note:'deductible 是最常考的保險術語'},
],
commonErrors:[
  {wrong:'I am suffering from a cold since last week.',right:'I have been suffering from a cold since last week.',explain:'since 表示持續狀態，要用現在完成進行式'},
  {wrong:'The insurance covers dental and vision.',right:'The insurance covers dental and vision care.',explain:'dental 和 vision 作名詞需要加 care 或 treatment'},
  {wrong:'Please fill up the prescription at the pharmacy.',right:'Please fill the prescription at the pharmacy.',explain:'fill a prescription（配藥）是固定說法，不加 up'},
],
examTips:[
  'Part 7 常考：保險說明書、醫療福利公告、診所廣告',
  'Part 3 常考：員工請病假、保險問題詢問、看診預約',
  'Part 4 常考：健康計畫公告、醫療保險說明',
  '高頻陷阱：premium（保費）/ deductible（自付額）/ copayment（就診自付）三個概念常混淆',
  '同義替換：checkup = physical examination；coverage = benefits',
  '關鍵字：insurance / coverage / deductible / prescription / wellness / copayment',
],
},

// ══════════════════════════════════
//  9. General Business 一般商務篇
// ══════════════════════════════════
{id:'general_biz',icon:'💼',name:'General Business',nameTw:'一般商務篇',color:'#5b8fd4',desc:'商務往來、合作、策略、簡報',
vocab:[
  {w:'proposal',m:'提案、企劃書',e:'We submitted a proposal to the client last week.',level:1},
  {w:'objective',m:'目標',e:'The main objective is to increase market share by 10%.',level:1},
  {w:'strategy',m:'策略',e:'The team developed a new marketing strategy for Q4.',level:1},
  {w:'stakeholder',m:'利害關係人',e:'All stakeholders were invited to the presentation.',level:1},
  {w:'revenue',m:'營收',e:'Revenue increased by 15% in the third quarter.',level:1},
  {w:'contract',m:'合約',e:'Both parties signed the contract yesterday morning.',level:1},
  {w:'fiscal year',m:'財政年度',e:'Our fiscal year ends on March 31st.',level:1},
  {w:'collaborate',m:'合作',e:'We will collaborate with a local firm on this project.',level:1},
  {w:'initiative',m:'主動、新計畫',e:'The company launched a new sustainability initiative.',level:1},
  {w:'benchmark',m:'基準、標竿',e:'We use industry benchmarks to evaluate our performance.',level:1},
  {w:'market share',m:'市場份額',e:'Our goal is to capture 20% of the market share.',level:1},
  {w:'networking',m:'建立人脈',e:'The conference is a great opportunity for networking.',level:1},
  {w:'clause',m:'條款',e:'Please review the confidentiality clause in the contract.',level:1},
  {w:'feasibility',m:'可行性',e:'A feasibility study was conducted before the project.',level:2},
  {w:'ROI',m:'投資報酬率',e:'The campaign delivered an ROI of 200%.',level:2},
  {w:'briefing',m:'簡報、情況說明',e:'The client briefing is scheduled for Tuesday morning.',level:2},
  {w:'counterpart',m:'對應的人/機構',e:'I will meet with my counterpart from the Paris office.',level:2},
  {w:'due diligence',m:'盡職調查',e:'Due diligence was completed before signing the agreement.',level:2},
  {w:'subsidiary',m:'子公司',e:'The subsidiary operates independently in Southeast Asia.',level:2},
  {w:'agenda',m:'議程、目標',e:'What is on the agenda for this quarter?',level:2},
  {w:'leverage',m:'善加利用、槓桿',e:'We can leverage our existing client base for growth.',level:2},
  {w:'turnaround',m:'轉虧為盈；快速完成',e:'The company achieved a remarkable turnaround in Q3.',level:2},
  {w:'boilerplate',m:'標準條款、制式內容',e:'The contract includes standard boilerplate language.',level:3},
  {w:'synergy',m:'綜效、協同效應',e:'The merger created synergy between the two teams.',level:3},
],
patterns:[
  {p:'We are pleased to announce + N/that',e:'We are pleased to announce the launch of our new product line.',t:'公告喜訊',tw:'我們很高興宣布…'},
  {p:'As per + N',e:'As per our agreement, payment is due within 30 days.',t:'根據…',tw:'根據我們的…'},
  {p:'We look forward to + V-ing',e:'We look forward to a long and productive partnership.',t:'期待合作',tw:'我們期待…'},
  {p:'This is to confirm that + S+V',e:'This is to confirm that the meeting has been rescheduled.',t:'確認事項',tw:'特此確認…'},
  {p:'Please find attached + N',e:'Please find attached the signed contract for your review.',t:'附件說明',tw:'附件請見…'},
  {p:'Should you have any questions, + V',e:'Should you have any questions, please do not hesitate to contact us.',t:'詢問邀請',tw:'如有任何問題，請…'},
  {p:'We would appreciate it if + S+V',e:'We would appreciate it if you could reply by end of this week.',t:'禮貌請求',tw:'如您能…，我們將不勝感激'},
  {p:'In accordance with + N',e:'In accordance with our policy, all returns must be approved.',t:'依照…',tw:'依照…'},
],
synonyms:[
  {word:'revenue',others:['income','earnings','sales','turnover','proceeds'],note:'revenue 最正式；turnover 常用於英式英語'},
  {word:'proposal',others:['plan','suggestion','offer','bid','pitch'],note:'proposal 較正式；pitch 是口語簡報用語'},
  {word:'strategy',others:['approach','plan','method','tactic','initiative'],note:'strategy（整體策略）；tactic（具體戰術）'},
  {word:'collaborate',others:['work together','partner','cooperate','team up','join forces'],note:'collaborate 最常考的商務合作動詞'},
  {word:'contract',others:['agreement','deal','arrangement','terms','accord'],note:'contract 強調法律文件；agreement 較廣義'},
],
commonErrors:[
  {wrong:'We are looking forward to cooperate with you.',right:'We are looking forward to cooperating with you.',explain:'look forward to 後面接動名詞（V-ing），不接原形動詞'},
  {wrong:'Please advice us on the next steps.',right:'Please advise us on the next steps.',explain:'advice 是名詞；advise 是動詞（給建議）'},
  {wrong:'The proposal was approved from the board.',right:'The proposal was approved by the board.',explain:'被動語態中「由…批准」用 by，不用 from'},
  {wrong:'We will discuss about the budget in tomorrow meeting.',right:"We will discuss the budget in tomorrow's meeting.",explain:'discuss 是及物動詞不加 about；tomorrow\'s 要加所有格'},
],
examTips:[
  'Part 7 常考：商務提案、合約條款、業績報告、商務 email',
  'Part 5 常考：商務詞彙的詞性、固定搭配介系詞',
  'Part 3/4 常考：會議簡報、客戶接待、業績報告',
  '高頻文體：email 開頭（I am writing to...）和結尾（Please do not hesitate to...）',
  '同義替換：revenue = income = earnings；collaborate = cooperate = work together',
  '關鍵字：proposal / revenue / stakeholder / fiscal year / initiative / ROI',
],
},

// ══════════════════════════════════
//  10. Manufacturing 製造業篇
// ══════════════════════════════════
{id:'manufacturing',icon:'🏭',name:'Manufacturing',nameTw:'製造業篇',color:'#9b7fe8',desc:'生產流程、品管、出貨、工廠作業',
vocab:[
  {w:'assembly line',m:'生產線',e:'The assembly line operates 24 hours a day.',level:1},
  {w:'defective',m:'有缺陷的',e:'Defective products are removed from the production line.',level:1},
  {w:'quality control',m:'品質管制',e:'Our quality control team inspects every production batch.',level:1},
  {w:'output',m:'產量',e:'We aim to increase output by 20% this quarter.',level:1},
  {w:'raw material',m:'原物料',e:'Rising costs of raw materials affect our profit margins.',level:1},
  {w:'shipment',m:'貨運批次',e:'The shipment arrived two days ahead of schedule.',level:1},
  {w:'inventory',m:'庫存',e:'We need to conduct a full inventory count this weekend.',level:1},
  {w:'compliance',m:'法規遵守',e:'The factory must maintain compliance with all safety regulations.',level:1},
  {w:'prototype',m:'原型、樣品',e:'Engineers are currently testing the new prototype.',level:1},
  {w:'throughput',m:'生產量、吞吐量',e:'We improved throughput by optimizing the workflow.',level:1},
  {w:'batch',m:'批次',e:'Each batch is tested before being released for shipment.',level:1},
  {w:'recall',m:'召回',e:'The company issued a voluntary recall of affected products.',level:1},
  {w:'specifications',m:'規格、規格書',e:'Products must meet all customer specifications.',level:1},
  {w:'yield',m:'產出率',e:'The yield rate improved from 92% to 97% after adjustments.',level:2},
  {w:'downtime',m:'停機時間',e:'Unexpected downtime costs the company $5,000 per hour.',level:2},
  {w:'foreman',m:'領班、工頭',e:'The foreman is responsible for supervising the production team.',level:2},
  {w:'calibrate',m:'校準',e:'Equipment must be calibrated at the start of each shift.',level:2},
  {w:'load capacity',m:'承載量',e:'The conveyor belt has a maximum load capacity of 500 kg.',level:2},
  {w:'vendor',m:'供應商',e:'We are evaluating three vendors for component supply.',level:2},
  {w:'ISO certification',m:'國際標準認證',e:'The factory achieved ISO 9001 certification last year.',level:2},
  {w:'lead time',m:'前置時間',e:'The lead time from order to delivery is three weeks.',level:2},
  {w:'just-in-time',m:'及時生產',e:'We use just-in-time manufacturing to reduce inventory costs.',level:2},
  {w:'tolerance',m:'（製造）容差',e:'Parts must be within a tolerance of 0.1 mm.',level:3},
  {w:'ergonomics',m:'人體工學',e:'Ergonomics improvements reduced workplace injuries by 30%.',level:3},
],
patterns:[
  {p:'The production of + N has been + adj',e:'The production of the new model has been temporarily delayed.',t:'生產狀況說明',tw:'…的生產已…'},
  {p:'In order to + V',e:'In order to meet demand, we increased production hours this week.',t:'目的說明',tw:'為了…'},
  {p:'All products must + V',e:'All products must pass a safety inspection before shipping.',t:'規定要求',tw:'所有產品必須…'},
  {p:'The factory will be shut down for + N',e:'The factory will be shut down for scheduled maintenance next Monday.',t:'停工公告',tw:'工廠將因…停工'},
  {p:'Due to a shortage of + N, + S+V',e:'Due to a shortage of components, production has been reduced.',t:'短缺說明',tw:'由於…短缺，…'},
  {p:'We have implemented + N to improve + N',e:'We have implemented new processes to improve product quality.',t:'改善措施',tw:'我們已實施…以改善…'},
  {p:'Workers are required to + V',e:'Workers are required to wear protective gear at all times.',t:'工作規定',tw:'員工須…'},
],
synonyms:[
  {word:'defective',others:['faulty','flawed','substandard','damaged','imperfect'],note:'defective 和 faulty 最常考，可互換'},
  {word:'shipment',others:['delivery','consignment','cargo','freight'],note:'shipment（一批貨）；delivery（送達動作）'},
  {word:'assembly line',others:['production line','manufacturing line'],note:'assembly line 和 production line 幾乎可互換'},
  {word:'output',others:['production','yield','throughput'],note:'output 最廣義；yield 強調良品率'},
],
commonErrors:[
  {wrong:'The products were manufactured with high quality.',right:'The products were manufactured to high quality standards.',explain:'製造「達到」高品質用 to，不用 with'},
  {wrong:'The factory will shut for maintenance.',right:'The factory will shut down for maintenance.',explain:'shutdown 需要加 down；shut alone 通常指關門'},
  {wrong:'The defect rate has been reduced of 20%.',right:'The defect rate has been reduced by 20%.',explain:'數量的增減用 by，不用 of'},
],
examTips:[
  'Part 4 常考：工廠公告、安全說明、生產進度、停工通知',
  'Part 7 常考：品管報告、出貨通知、製程說明、召回公告',
  'Part 3 常考：生產線問題討論、供應商協商',
  '高頻題型：圖表題（生產數量/良率圖）',
  '同義替換：defective = faulty；shipment = delivery；output = production',
  '關鍵字：assembly line / quality control / defective / inventory / compliance / recall',
],
},

// ══════════════════════════════════
//  11. Corporate Development 企業發展篇
// ══════════════════════════════════
{id:'corporate',icon:'📈',name:'Corporate Development',nameTw:'企業發展篇',color:'#e8b86d',desc:'合併收購、企業策略、組織變革',
vocab:[
  {w:'merger',m:'合併',e:'The merger was approved by shareholders last month.',level:1},
  {w:'acquisition',m:'收購',e:'The company announced the acquisition of a startup.',level:1},
  {w:'restructuring',m:'重組',e:'The restructuring plan will reduce costs significantly.',level:1},
  {w:'subsidiary',m:'子公司',e:'They opened a wholly-owned subsidiary in Singapore.',level:1},
  {w:'shareholder',m:'股東',e:'Shareholders will vote on the merger next week.',level:1},
  {w:'board of directors',m:'董事會',e:'The board of directors approved the new strategy unanimously.',level:1},
  {w:'expansion',m:'擴張',e:"The company's expansion into Asia has been successful.",level:1},
  {w:'headquarters',m:'總部',e:'The headquarters will relocate to New York next year.',level:1},
  {w:'stock',m:'股票',e:"The company's stock rose 5% after the announcement.",level:1},
  {w:'annual report',m:'年報',e:'The annual report highlights record-breaking revenue.',level:1},
  {w:'joint venture',m:'合資企業',e:'The two companies formed a joint venture in Vietnam.',level:1},
  {w:'equity',m:'股東權益',e:'The startup raised $5M through equity financing.',level:1},
  {w:'downsizing',m:'裁員、縮編',e:'Downsizing affected 200 employees across three departments.',level:2},
  {w:'IPO',m:'首次公開募股',e:'The company plans an IPO on the New York Stock Exchange.',level:2},
  {w:'due diligence',m:'盡職調查',e:'Due diligence is required before any major acquisition.',level:2},
  {w:'franchise',m:'特許經營',e:'The brand expanded through a franchise model.',level:2},
  {w:'takeover',m:'接管、收購',e:'The hostile takeover attempt was rejected by the board.',level:2},
  {w:'spin-off',m:'分拆子公司',e:'The IT division was spun off as an independent company.',level:2},
  {w:'brand equity',m:'品牌價值',e:'Years of quality service have built strong brand equity.',level:2},
  {w:'liquidation',m:'清算',e:'The failing company went into liquidation last quarter.',level:2},
  {w:'divestiture',m:'資產剝離',e:'The divestiture of non-core assets raised $50 million.',level:3},
  {w:'conglomerate',m:'集團企業',e:'The conglomerate operates in 12 different industries.',level:3},
],
patterns:[
  {p:'Following the + N',e:'Following the merger, all employees will be transferred.',t:'合併後',tw:'在…之後'},
  {p:'The company plans to + V',e:'The company plans to expand operations into three new markets.',t:'企業計畫',tw:'公司計畫…'},
  {p:'Effective immediately, + S+V',e:'Effective immediately, all travel requests must be pre-approved.',t:'立即生效',tw:'即日起…'},
  {p:'As part of the + N, + S+V',e:'As part of the restructuring, two departments will be merged.',t:'重組說明',tw:'作為…的一部分…'},
  {p:'The board has voted to + V',e:'The board has voted to approve the acquisition of XYZ Corp.',t:'董事會決議',tw:'董事會投票決定…'},
  {p:'Shareholders are advised that + S+V',e:'Shareholders are advised that dividends will be increased this year.',t:'股東通知',tw:'建議股東注意…'},
  {p:'The transition is expected to + V',e:'The transition is expected to be completed by end of Q2.',t:'過渡期',tw:'過渡期預計…'},
  {p:'In an effort to + V, + S+V',e:'In an effort to cut costs, the company is reducing its workforce.',t:'努力目標',tw:'為了…，…'},
],
synonyms:[
  {word:'merger',others:['consolidation','union','amalgamation'],note:'merger（雙方合意合併）≠ acquisition（一方收購另一方）'},
  {word:'shareholder',others:['stockholder','investor','equity holder'],note:'shareholder 和 stockholder 可互換'},
  {word:'headquarters',others:['head office','main office','HQ','corporate office'],note:'HQ 是縮寫，口語常用'},
  {word:'restructuring',others:['reorganization','downsizing','rightsizing','realignment'],note:'restructuring 最中性；downsizing 強調縮減規模'},
],
commonErrors:[
  {wrong:'The company will merge with ABC Corp next year.',right:'The company will merge with ABC Corp next year.',explain:'這句是正確的，merge with 是標準用法'},
  {wrong:'The board approved to acquire the company.',right:'The board approved the acquisition of the company.',explain:'approve 後面接名詞（the acquisition），不接不定詞'},
  {wrong:'The shareholders voted for the merge.',right:'The shareholders voted for the merger.',explain:'合併作名詞是 merger，不是 merge'},
],
examTips:[
  'Part 4 常考：公司公告（合併/重組/遷址）、員工大會宣布',
  'Part 7 常考：股東信、年報摘要、合併說明、新聞稿',
  'Part 3 常考：主管間討論策略、告知部門變動',
  '高頻文體：press release（新聞稿）格式和用語',
  '同義替換：merger = consolidation；headquarters = HQ = head office',
  '關鍵字：merger / acquisition / restructuring / subsidiary / shareholder / joint venture',
],
},

// ══════════════════════════════════
//  12. Technical Areas 技術層面篇
// ══════════════════════════════════
{id:'technical',icon:'💻',name:'Technical Areas',nameTw:'技術層面篇',color:'#5b8fd4',desc:'IT、工程、技術支援、系統操作',
vocab:[
  {w:'software',m:'軟體',e:'The new software update will be released next week.',level:1},
  {w:'troubleshoot',m:'排除故障',e:'Our IT team will troubleshoot the network issue.',level:1},
  {w:'install',m:'安裝',e:'Please install the latest version of the application.',level:1},
  {w:'upgrade',m:'升級',e:'All computers will be upgraded to the new operating system.',level:1},
  {w:'backup',m:'備份',e:'Data backup is performed automatically every night.',level:1},
  {w:'database',m:'資料庫',e:'The database stores all customer records and order history.',level:1},
  {w:'server',m:'伺服器',e:'The server went down for scheduled maintenance last night.',level:1},
  {w:'glitch',m:'小故障、異常',e:'There was a minor glitch in the payment system.',level:1},
  {w:'firewall',m:'防火牆',e:'The firewall successfully blocked unauthorized access.',level:1},
  {w:'bandwidth',m:'頻寬',e:'We need more bandwidth to support remote work.',level:1},
  {w:'downtime',m:'系統停機時間',e:'The scheduled downtime will last approximately two hours.',level:1},
  {w:'log in/out',m:'登入/登出',e:'Please log out of all systems before leaving the office.',level:1},
  {w:'interface',m:'介面',e:'The new user interface is much more intuitive.',level:1},
  {w:'cybersecurity',m:'網路安全',e:'Cybersecurity training is mandatory for all employees.',level:2},
  {w:'encryption',m:'加密',e:'All sensitive data is protected by encryption.',level:2},
  {w:'cloud',m:'雲端',e:'We migrated all data to cloud storage last year.',level:2},
  {w:'patch',m:'修補程式',e:'Apply the security patch immediately to prevent vulnerabilities.',level:2},
  {w:'configuration',m:'組態設定',e:'The system configuration was changed by the IT team.',level:2},
  {w:'data breach',m:'資料外洩',e:'The company reported a data breach affecting 10,000 users.',level:2},
  {w:'IT infrastructure',m:'IT 基礎設施',e:'Upgrading the IT infrastructure will cost $2 million.',level:2},
  {w:'VPN',m:'虛擬私人網路',e:'Use the VPN when accessing company files remotely.',level:2},
  {w:'legacy system',m:'舊有系統',e:'The legacy system is being replaced by modern software.',level:3},
  {w:'API',m:'應用程式介面',e:'The new API allows third-party integration.',level:3},
],
patterns:[
  {p:'The system will be + adj + for + 時間',e:'The system will be unavailable for approximately two hours.',t:'系統維護說明',tw:'系統將…'},
  {p:'If you experience + N, please + V',e:'If you experience any login issues, please contact IT support.',t:'問題處理指引',tw:'如果你遇到…，請…'},
  {p:'We apologize for any + N + caused by + N',e:'We apologize for any inconvenience caused by the system outage.',t:'道歉說明',tw:'為…造成的…致歉'},
  {p:'Users are advised to + V',e:'Users are advised to change their passwords immediately.',t:'使用者提醒',tw:'使用者應…'},
  {p:'The issue has been resolved and + S+V',e:'The issue has been resolved and all systems are fully operational.',t:'問題解決公告',tw:'問題已解決，…'},
  {p:'To ensure + N, please + V',e:'To ensure data security, please enable two-factor authentication.',t:'確保安全',tw:'為確保…，請…'},
  {p:'Access to + N will be restricted + 時間',e:'Access to the network will be restricted during the upgrade.',t:'存取限制',tw:'…期間，對…的存取將受限制'},
],
synonyms:[
  {word:'troubleshoot',others:['diagnose','fix','resolve','debug','address'],note:'troubleshoot 最常考的IT動詞'},
  {word:'upgrade',others:['update','improve','enhance','modernize'],note:'upgrade（較大版本升級）；update（小幅更新）'},
  {word:'downtime',others:['outage','interruption','unavailability','maintenance window'],note:'outage 強調非預期中斷；downtime 可以是計劃內'},
  {word:'glitch',others:['bug','error','malfunction','issue','problem'],note:'glitch 是較口語的輕微故障'},
],
commonErrors:[
  {wrong:'The system is currently in maintenance.',right:'The system is currently undergoing maintenance.',explain:'維修進行中用 undergo maintenance，不說 in maintenance'},
  {wrong:'Please update your password for security purpose.',right:'Please update your password for security purposes.',explain:'purpose 在此表達原因時通常用複數 purposes'},
  {wrong:'The IT team fixed the problem of the network.',right:'The IT team fixed the network problem.',explain:'修飾名詞用名詞作形容詞（network problem），較自然'},
],
examTips:[
  'Part 4 常考：系統維護公告、IT 變更通知、網路中斷說明',
  'Part 7 常考：技術手冊摘要、IT 支援 email、系統更新公告',
  'Part 3 常考：技術問題討論、IT 支援通話',
  '高頻題型：What will happen during the maintenance? = 後續行動題',
  '同義替換：troubleshoot = fix = resolve；downtime = outage；glitch = bug',
  '關鍵字：troubleshoot / upgrade / backup / server / glitch / cybersecurity / downtime',
],
},

// ══════════════════════════════════
//  13. Financing 財務金融篇
// ══════════════════════════════════
{id:'financing',icon:'💰',name:'Financing',nameTw:'財務金融篇',color:'#4caf82',desc:'財報、預算、投資、貸款、會計',
vocab:[
  {w:'budget',m:'預算',e:'The annual budget was approved by the board of directors.',level:1},
  {w:'expenditure',m:'支出、費用',e:'We need to reduce our monthly expenditures by 15%.',level:1},
  {w:'profit margin',m:'利潤率',e:'Our profit margin improved by 3% this quarter.',level:1},
  {w:'cash flow',m:'現金流',e:'Maintaining positive cash flow is critical for small businesses.',level:1},
  {w:'audit',m:'審計、查帳',e:'The external audit found no significant issues this year.',level:1},
  {w:'balance sheet',m:'資產負債表',e:'The balance sheet shows total assets of $5 million.',level:1},
  {w:'dividend',m:'股息',e:'Shareholders will receive a dividend of $2 per share.',level:1},
  {w:'liability',m:'負債',e:"The company's total liabilities exceed its current assets.",level:1},
  {w:'depreciation',m:'折舊',e:'Equipment depreciation must be recorded annually.',level:1},
  {w:'equity',m:'股東權益',e:'They raised capital through equity financing.',level:1},
  {w:'fiscal quarter',m:'財政季度',e:'Q3 results exceeded targets across all divisions.',level:1},
  {w:'net income',m:'淨收入',e:'Net income after taxes was $1.2 million last year.',level:1},
  {w:'accounts payable',m:'應付帳款',e:'Accounts payable must be cleared within 60 days.',level:1},
  {w:'accounts receivable',m:'應收帳款',e:'Accounts receivable totals $2.3 million this quarter.',level:1},
  {w:'overhead',m:'管銷費用',e:'We are looking for ways to reduce overhead costs.',level:2},
  {w:'amortization',m:'分期攤還',e:'Loan amortization is spread over 10 years.',level:2},
  {w:'collateral',m:'擔保品',e:'The bank required property as collateral for the loan.',level:2},
  {w:'interest rate',m:'利率',e:'The loan carries a fixed interest rate of 3.5%.',level:2},
  {w:'portfolio',m:'投資組合',e:'The investment portfolio performed well despite market volatility.',level:2},
  {w:'write-off',m:'沖銷、呆帳',e:'The uncollectible debt was written off last fiscal year.',level:2},
  {w:'earnings per share',m:'每股盈餘（EPS）',e:'Earnings per share increased to $3.45 in the latest quarter.',level:2},
  {w:'capital expenditure',m:'資本支出（CapEx）',e:'Capital expenditure for new equipment was $2 million.',level:2},
  {w:'liquidity',m:'流動性',e:'The company maintains strong liquidity for unexpected costs.',level:3},
  {w:'fiscal deficit',m:'財政赤字',e:'The department ran a fiscal deficit for the second year.',level:3},
],
patterns:[
  {p:'According to the + 文件',e:'According to the quarterly report, revenue increased by 12%.',t:'引用數據',tw:'根據…'},
  {p:'The budget for + N + is + $',e:'The budget for marketing activities this year is $500,000.',t:'預算說明',tw:'…的預算為…'},
  {p:'We expect + N/that + S+V',e:'We expect profits to exceed targets this fiscal quarter.',t:'財務預測',tw:'我們預期…'},
  {p:'Compared to the same period last year',e:'Compared to the same period last year, revenue grew by 18%.',t:'同期比較',tw:'與去年同期相比'},
  {p:'Operating costs have + V-ed by + %',e:'Operating costs have decreased by 8% due to process improvements.',t:'成本說明',tw:'營運成本已…%'},
  {p:'The company has allocated + $ for + N',e:'The company has allocated $2M for research and development.',t:'撥款說明',tw:'公司已撥款$…用於…'},
  {p:'Earnings per share + V-ed to + $',e:'Earnings per share increased to $3.45 in the latest quarter.',t:'每股盈餘',tw:'每股盈餘…至$…'},
  {p:'The financial results reflect + N',e:'The financial results reflect strong demand in emerging markets.',t:'財報解讀',tw:'財務結果反映…'},
],
synonyms:[
  {word:'revenue',others:['income','earnings','sales','turnover','receipts'],note:'revenue 最常考；turnover 是英式英語常見說法'},
  {word:'expenditure',others:['expense','cost','spending','outlay'],note:'expenditure 最正式；expense 最常用'},
  {word:'audit',others:['review','examination','inspection','assessment'],note:'audit 特指財務查帳；review 較廣義'},
  {word:'budget',others:['financial plan','allocation','funding','appropriation'],note:'budget 是多益最常考的財務名詞'},
  {word:'liability',others:['debt','obligation','amount owed'],note:'liability（負債）≠ asset（資產），考試常考對立'},
],
commonErrors:[
  {wrong:'The company is in profit this year.',right:'The company is profitable this year. / The company made a profit this year.',explain:'in profit 不是標準說法；用 profitable 或 made a profit'},
  {wrong:'Revenue was increased by 10% last quarter.',right:'Revenue increased by 10% last quarter.',explain:'revenue increase 通常用主動語態，不需要被動'},
  {wrong:'Accounts payable means the money others owe us.',right:'Accounts receivable means the money others owe us.',explain:'AP（應付）= 我欠別人；AR（應收）= 別人欠我，這是最常搞錯的一對'},
  {wrong:'The budget has been over-spent of $5,000.',right:'The budget has been exceeded by $5,000. / We overspent by $5,000.',explain:'超出預算用 exceed the budget 或 overspend'},
],
examTips:[
  'Part 7 常考：財報、預算報告、投資說明、貸款條件',
  'Part 5 常考：財務詞彙的詞性（noun/adj/verb）、固定搭配',
  'Part 3/4 常考：財務會議、預算審核、業績報告',
  '高頻題型：圖表整合題（季度業績圖/預算分配圖）',
  '同義替換：revenue = income = earnings；expenditure = expense = cost',
  'Ch16 重點：Part2 Q17/Q24, Part3 Q68-70, Part4 Q98-100, Part5 Q112/Q120, Part7 Q168-171',
  '最常混淆：accounts payable（應付 = 我欠別人）≠ accounts receivable（應收 = 別人欠我）',
],
},

]; // end window.TOPICS_DATA
